apiVersion: apps/v1
kind: Deployment
metadata:
  name: elgg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elgg-app
  template:
    metadata:
      labels:
        app: elgg-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s01-mng-1008c2-k8s01-mng-worker-2
      securityContext:
        fsGroup: 33
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["/bin/sh", "-c", "chown -R 33:33 /var/elgg_data && chmod -R 775 /var/elgg_data"]
        #fichiers de configuration
        # command: ["/bin/sh", "-c", "chown -R 33:33 /var/www/html/elgg/elgg-config && chmod -R 775 /var/www/html/elgg/elgg-config"]
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data

        # - mountPath: /var/www/html/elgg/elgg-config
        #   name: elgg-config-volume

      containers:
      - name: elgg-app
        image: bitaouioussama/elgg-app:v6
        imagePullPolicy: Always
        securityContext:
          runAsUser: 33
          runAsGroup: 33
        envFrom:
          - secretRef:
              name: elgg-env
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "800m"
            memory: "700Mi"
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data
      volumes:
      - name: elgg-data
        persistentVolumeClaim:
          claimName: elgg-pvc

---


apiVersion: v1
kind: Service
metadata:
  name: elgg-app
spec:
  type: NodePort
  selector:
    app: elgg-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80