apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default-storageclass"
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elgg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default-storageclass"
  #local-path
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elgg-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default-storageclass"
  resources:
    requests:
      storage: 20Gi
