// FR lang variables

tinyMCE.addToLang('style',{
title : 'Edtiteur de style CSS',
styleinfo_desc : 'Edtiteur de style CSS',
apply : 'Appliquer',
text_tab : 'Texte',
background_tab : 'Fond',
block_tab : 'Bloc',
box_tab : 'Boite',
border_tab : 'Bord',
list_tab : 'Liste',
positioning_tab : 'Positionnement',
text_props : 'Texte',
text_font : 'Fonte',
text_size : 'Taille',
text_weight : 'Poid',
text_style : 'Style',
text_variant : 'Variant',
text_lineheight : 'Hauteur de ligne',
text_case : 'Casse',
text_color : 'Couleur',
text_decoration : 'Décoration',
text_overline : 'surligné',
text_underline : 'souligné',
text_striketrough : 'barré',
text_blink : 'clignotant',
text_none : 'aucun',
background_color : 'Couleur de fond',
background_image : 'Image de fond',
background_repeat : 'Répéter',
background_attachment : 'Attacher',
background_hpos : 'Position horizontal',
background_vpos : 'Position vertical',
block_wordspacing : 'Espace entre les mots',
block_letterspacing : 'Espace entre les lettres',
block_vertical_alignment : 'Aligenement vertical',
block_text_align : 'Aligement du texte',
block_text_indent : 'Indentation du texte',
block_whitespace : 'Espace',
block_display : 'Afficher',
box_width : 'Largeur',
box_height : 'Hauteur',
box_float : 'Float',
box_clear : 'Clear',
padding : 'Padding',
same : 'Identique pour tous',
top : 'Haut',
right : 'Droite',
bottom : 'Bas',
left : 'Gauche',
margin : 'Marge',
style : 'Style',
width : 'Largeur',
height : 'Hauteur',
color : 'Couleur',
list_type : 'Type',
bullet_image : 'Bullet image',
position : 'Position',
positioning_type : 'Type',
visibility : 'Visibilité',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Placement',
clip : 'Clip'
});
