// RU lang variables UTF-8

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Цитирование',
abbr_desc : 'Аббревиатура',
acronym_desc : 'Акроним',
del_desc : 'Стирание',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ИД',
attribute_label_class : 'Класс',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Цитировать',
attribute_label_datetime : 'Дата/Время',
attribute_label_langdir : 'Направление Текста',
attribute_option_ltr : 'Слева направо',
attribute_option_rtl : 'Справа налево',
attribute_label_langcode : 'Язык',
general_tab : 'Основной',
attrib_tab : 'Атрибуты',
events_tab : 'События',
fieldset_general_tab : 'Основные Установки',
fieldset_attrib_tab : 'Элемент Атрибуты',
fieldset_events_tab : 'Элемент События',
title_ins_element : 'Элемент Вставка',
title_del_element : 'Элемент События',
title_acronym_element : 'Элемент Акроним',
title_abbr_element : 'Элемент Аббревиатура',
title_cite_element : 'Элемент Цитирование',
remove : 'Убрать',
not_set : '--не установлен--',
insert_date : 'Вставить текущие дату/время'
});
