filter:
    excluded_paths:
        - 'vendors/*'
        - '*/vendors/*'
        - '*/tests/*'
        - '*/vendor/*'
tools:
    external_code_coverage: true
    js_hint:
        filter:
            excluded_paths: ['vendors/*','*/vendors/*','*/tests/*','*/vendor/*']
    php_mess_detector:
        filter:
            excluded_paths: ['vendors/*','*/vendors/*','*/tests/*','*/vendor/*']
    sensiolabs_security_checker: true
    php_pdepend:
        excluded_dirs:
            - vendors
            - vendor
    external_code_coverage:
        timeout: '600'
    php_hhvm: true
    php_sim: true

    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_cpd: false
