<?php

return [
	'admin/delete_admin_notices' => ['access' => 'admin'],
	'admin/menu/save' => ['access' => 'admin'],
	'admin/plugins/activate' => ['access' => 'admin'],
	'admin/plugins/activate_all' => ['access' => 'admin'],
	'admin/plugins/deactivate' => ['access' => 'admin'],
	'admin/plugins/deactivate_all' => ['access' => 'admin'],
	'admin/plugins/set_priority' => ['access' => 'admin'],
	'admin/security/settings' => ['access' => 'admin'],
	'admin/security/regenerate_site_secret' => ['access' => 'admin'],
	'admin/site/cache/invalidate' => ['access' => 'admin'],
	'admin/site/flush_cache' => ['access' => 'admin'],
	'admin/site/icons' => ['access' => 'admin'],
	'admin/site/set_maintenance_mode' => ['access' => 'admin'],
	'admin/site/set_robots' => ['access' => 'admin'],
	'admin/site/unlock_upgrade' => ['access' => 'admin'],
	'admin/site/settings' => ['access' => 'admin'],
	'admin/upgrade' => ['access' => 'admin'],
	'admin/upgrade/reset' => ['access' => 'admin'],
	'admin/user/ban' => ['access' => 'admin'],
	'admin/user/bulk/ban' => ['access' => 'admin'],
	'admin/user/bulk/delete' => ['access' => 'admin'],
	'admin/user/bulk/unban' => ['access' => 'admin'],
	'admin/user/bulk/validate' => ['access' => 'admin'],
	'admin/user/change_email' => ['access' => 'admin'],
	'admin/user/delete' => ['access' => 'admin'],
	'admin/user/login_as' => ['access' => 'admin'],
	'admin/user/logout_as' => [],
	'admin/user/makeadmin' => ['access' => 'admin'],
	'admin/user/resetpassword' => ['access' => 'admin'],
	'admin/user/removeadmin' => ['access' => 'admin'],
	'admin/user/unban' => ['access' => 'admin'],
	'admin/user/validate' => ['access' => 'admin'],
	'annotation/delete' => [],
	'avatar/upload' => [],
	'comment/save' => [],
	'diagnostics/download' => ['access' => 'admin'],
	'entity/delete' => [],
	'entity/mute' => [],
	'entity/subscribe' => [],
	'entity/unmute' => [],
	'entity/unsubscribe' => [],
	'login' => ['access' => 'logged_out'],
	'logout' => [],
	'notifications/mute' => ['access' => 'public'],
	'plugins/settings/remove' => ['access' => 'admin'],
	'plugins/settings/save' => ['access' => 'admin'],
	'plugins/usersettings/save' => [],
	'river/delete' => [],
	'settings/notifications' => [],
	'settings/notifications/subscriptions' => [],
	'user/changepassword' => ['access' => 'public'],
	'user/requestnewpassword' => ['access' => 'public'],
	'useradd' => ['access' => 'admin'],
	'usersettings/save' => [],
	'widgets/add' => [],
	'widgets/delete' => [],
	'widgets/move' => [],
	'widgets/save' => [],
];
