// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('fullpage',{
	title : 'Thuộc tính văn bản',
	desc : 'Thuộc tính văn bản',
	meta_tab : 'Chung',
	appearance_tab : 'Xuất hiện',
	advanced_tab : 'Nâng cao',
	meta_props : 'Thông tin siêu dữ liệu',
	langprops : 'Ngôn ngữ và bộ mã',
	meta_title : 'Tiêu đề',
	meta_keywords : 'Từ khóa',
	meta_description : 'Mô tả',
	meta_robots : 'Robots',
	doctypes : 'Doctype',
	langcode : 'Mã ngôn ngữ',
	langdir : 'Hướng ngôn ngữ',
	ltr : 'Trái sang phải',
	rtl : 'Phải sang trái',
	xml_pi : 'Khai báo XML',
	encoding : 'Bộ mã ký tự',
	appearance_bgprops : 'Thuộc tính nền',
	appearance_marginprops : 'Lề',
	appearance_linkprops : 'Màu liên kết',
	appearance_textprops : 'Thuộc tính văn bản',
	bgcolor : 'Màu nền',
	bgimage : 'Ảnh nền',
	left_margin : 'Lề trái',
	right_margin : 'Lề phải',
	top_margin : 'Lề trên',
	bottom_margin : 'Lề dưới',
	text_color : 'Màu văn bản',
	font_size : 'Kích thước font chữ',
	font_face : 'Tên font',
	link_color : 'Màu liên kết',
	hover_color : 'Màu khi di chuột lên',
	visited_color : 'Màu khi đã ghé thăm',
	active_color : 'Màu khi nhấn',
	textcolor : 'Màu chữ',
	fontsize : 'Kích thước font chữ',
	fontface : 'Tên font',
	meta_index_follow : 'Chỉ mục và theo các liên kết',
	meta_index_nofollow : 'Chỉ mục và không theo các liên kết',
	meta_noindex_follow : 'Không phải chỉ mục nhưng theo các liên kết',
	meta_noindex_nofollow : 'Không phải chỉ mục và không theo các liên kết',
	appearance_style : 'Đinh dạng phong cách và thuộc tính phong cách',
	stylesheet : 'Định dạng phong cách',
	style : 'Phong cách',
	author : 'Tác giả',
	copyright : 'Bản quyền',
	add : 'Thêm một thành phần mới',
	remove : 'Xóa thành phần đã chọn',
	moveup : 'Di chuyển thành phần đã chọn lên trên',
	movedown : 'Di chuyển thành phần đã chọn xuống dưới',
	head_elements : 'Mục đầu',
	info : 'Thông tin',
	info_text : '',
	add_title : 'Thành phần tiêu đề',
	add_meta : 'Thành phần siêu dữ liệu',
	add_script : 'Thành phần Script',
	add_style : 'Thành phần phong cách',
	add_link : 'Thành phần liên kết',
	add_base : 'Thành phần cơ sở',
	add_comment : 'Nút chú thích',
	title_element : 'Thành phần tiêu đề',
	script_element : 'Thành phần Script',
	style_element : 'Thành phần phong cách',
	base_element : 'Thành phần cơ sở',
	link_element : 'Thành phần liên kết',
	meta_element : 'Thành phần siêu dữ liệu',
	comment_element : 'Chú thích',
	src : 'Src',
	language : 'Ngôn ngữ',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Type',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Properties',
	name : 'Name',
	value : 'Value',
	content : 'Content',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'General',
	advanced_props : 'Advanced',
	delta_width : 0,
	delta_height : 0
});
