// PL lang variables
// fixed by Wooya
// http://www.mfusion.prv.pl
// fixed by lemiel 14.11.2005

tinyMCE.addToLang('advlink',{
general_tab : 'Główne ustawienia',
popup_tab : 'Okienko popup',
events_tab : 'Zdarzenia',
advanced_tab : 'Zaawansowane',
general_props : 'Główne',
popup_props : 'Ustawienia popup',
event_props : 'Zdarzenia',
advanced_props : 'Zaawansowane opcje',
popup_opts : 'Opcje',
anchor_names : 'Kotwice',
target_same : 'Otwórz w tym oknie / ramce',
target_parent : 'Otwórz w poprzednim oknie / ramce',
target_top : 'Otwórz w głównej ramce (zamienia wszystkie ramki)',
target_blank : 'Otwórz w nowym oknie',
popup : 'Okienko popup Javascript',
popup_url : 'URL dla popup',
popup_name : 'Nazwa okna',
popup_return : 'Wstaw \'return false\'',
popup_scrollbars : 'Pokaż paski przewijania',
popup_statusbar : 'Pokaż pasek statusu',
popup_toolbar : 'Pokaż pasek narzędzi',
popup_menubar : 'Pokaż pasek menu',
popup_location : 'Pokaż pasek adresu',
popup_resizable : 'Pozwalaj na zmianę wielkości okna',
popup_dependent : 'Zależne (tylko Mozilla/Firefox)',
popup_size : 'Rozmiar',
popup_position : 'Pozycja (X/Y)',
id : 'Id',
style: 'Styl',
classes : 'Klasa',
target_name : 'Nazwa celu',
langdir : 'Kierunek tekstu',
target_langcode : 'Język celu',
langcode : 'Kod języka',
encoding : 'Kodowanie znaków celu',
mime : 'Typ MIME celu',
rel : 'Zależność strony do celu',
rev : 'Zależność celu do strony',
tabindex : 'Indeks tabeli',
accesskey : 'Klawisz dostępu',
ltr : 'Lewy do prawego',
rtl : 'Prawy do lewego'
});
