// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('advlink',{
general_tab : 'Chung',
popup_tab : 'Cửa sổ bật ra',
events_tab : 'Sự kiện',
advanced_tab : 'Nâng cao',
general_props : 'Thuộc tính chung',
popup_props : 'Thuộc tính bật ra',
event_props : 'Sự kiện',
advanced_props : 'Thuộc tính nâng cao',
popup_opts : 'Tùy chọn',
anchor_names : 'Neo',
target_same : 'Mở trong cửa sổ / khung này',
target_parent : 'Mở trong cửa sổ / khung cha',
target_top : 'Mở trong khung cao nhất (thay thế mọi khung)',
target_blank : 'Mở trong cửa sổ mới',
popup : 'Cửa sổ bật ra Javascript',
popup_url : 'Địa chỉ bật ra',
popup_name : 'Tên cửa sổ',
popup_return : 'Thêm \'return false\'',
popup_scrollbars : 'Hiện thanh cuộn',
popup_statusbar : 'Hiện thanh trạng thái',
popup_toolbar : 'Hiện thanh công cụ',
popup_menubar : 'Hiện thanh menu',
popup_location : 'Hiện thanh địa chỉ',
popup_resizable : 'Cửa sổ có thể thay đổi kích thước',
popup_dependent : 'Độc lập (chỉ trên Mozilla/Firefox)',
popup_size : 'Kích thước',
popup_position : 'Vị trí (tọa độ X/Y)',
id : 'Id',
style: 'Phong cách',
classes : 'Lớp',
target_name : 'Tên mục tiêu',
langdir : 'Hướng ngôn ngữ',
target_langcode : 'Ngôn ngữ mục tiêu',
langcode : 'Mã ngôn ngữ',
encoding : 'Mã hóa kí tự mục tiêu',
mime : 'Kiểu MIME mục tiêu',
rel : 'Quan hệ trang đến mục tiêu',
rev : 'Quan hệ mục tiêu đến trang',
tabindex : 'Chỉ số Tab',
accesskey : 'Phím truy cập',
ltr : 'Trái sang phải',
rtl : 'Phải sang trái'
});
