<?php 
    /**
     * TOS agreement
     **/
?>
<div class="mainContent_nosidebar_box_top"><h1>Terms of Service</h1></div>
<div class="mainContent_nosidebar_box_bottom">

<p><b>We want to provide you with valuable services through our site, we don't want you to receive spam, download malicious programmes, be harassed, insulted and want your experience on the site to be always secure.</b></p>
<p><b>That's why we created these Terms of Service.</b></p>
<p><b>PLEASE READ THESE TERMS OF SERVICE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AND CLAUSES ON HOW DISPUTES WILL BE RESOLVED.</b></p>
<p><b>By using the UnLtdWorld site, you are agreeing with the following Terms of Service (TOS).</b></p>
<p><b>Terms of Service</b></p>
<p>Welcome to UnLtdWorld. UnLtdWorld is an online platform that empowers and helps people to generate greater social impact in the real world by enabling them to share, shape and build knowledge, markets and communities through social networks. The UnLtdWorld service, site and network (collectively, "UnLtdWorld" or "the Service" or "the Site") are operated by UnLtd (a registered charity, number 1090393 and our company registration number is 4180639) and its corporate affiliates (collectively, "us", "we" or "the Company" or "UnLtdWorld"). By accessing or using our web site at www.unltdworld.com, you (the "User") signify that you have read, understand and agree to be bound by these Terms of Service ("Terms of Service" or "Terms of Use" or "Agreement"), whether or not you are a registered member of UnLtdWorld. We reserve the right, at our sole discretion, to change, modify, add, or delete portions of these Terms of Service at any time without further notice. If we do this, we will post the changes to these Terms of Service on this page and will indicate at the top of this page the date these terms were last revised. Your continued use of the Service or the Site after any such changes constitutes your acceptance of the new Terms of Service. If you do not agree to abide by these or any future Terms of Use, do not use or access (or continue to use or access) the Service or the Site. It is your responsibility to regularly check the Site to determine if there have been changes to these Terms of Service and to review such changes.</p>

<ol>
<li><b>Description of Services</b><br />
    <p>UnLtdWorld currently provides users with access to a rich collection of resources, including various communications tools, applications, databases of information, collections of services and content through its web site(s) (the "Service"). Unless explicitly stated otherwise, any new feature that augment or enhance the current Service, including the release of new UnLtdWorld applications and features, shall be subject to the Terms of Service.</p>
</li>
<li><b>Eligibility</b><br />
    <p>Membership in the Service is void where prohibited. This Site is intended solely for users who are thirteen (13) years of age or older. Any registration by, use of or access to the Site by anyone under 13 is unauthorized, unlicensed and in violation of these Terms of Use. By using the Service or the Site, you represent and warrant that you are 13 or older, and that you agree to and to abide by all of the terms and conditions of this Agreement.</p>
</li>
<li><b>Registration Data; Account Security</b><br />
    <p>In consideration of your use of the Site, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the Site ("Registration Data"); (b) maintain the security of your password and identification; (c) maintain and promptly update the Registration Data, and any other information you provide to Company, to keep it accurate, current and complete; and (d) be fully responsible for all use of your account and for any actions that take place using your account. If you provide any information that is untrue, inaccurate, not current or incomplete, or The Company has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, The Company has the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof).</p>

</li>
<li><b>Member account, password, and security</b><br />
    <p>You select a username and password upon completing the Service's registration process. You are responsible for maintaining the confidentiality of your password, and are fully responsible for all activities that occur under your password. You agree to (a) immediately notify UnLtdWorld of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. UnLtdWorld cannot and will not be liable for any loss or damage arising from your failure to comply with this Section.</p>
</li>
<li><b>Proprietary Rights in Site Content; Limited License</b><br />
    <p>All content on the Site and available through the Service, including but not limited to designs, text, graphics, pictures, video, information, applications, software, music, sound and other files, and their selection and arrangement (the "Site Content"), are the proprietary property of the Company, its users or its licensors with all rights reserved. No Site Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without the Company's prior written permission, except that the foregoing does not apply to your own User Content that you legally post on the Site. Provided that you are eligible for use of the Site, you are granted a limited license to access and use the Site and the Site Content and to download or print a copy of any portion of the Site Content to which you have properly gained access solely for your personal, non-commercial use, provided that you keep all copyright or other proprietary notices intact. Except for your own User Content, you may not upload or republish Site Content on any Internet, Intranet or Extranet site or incorporate the information in any other database or compilation, and any other use of the Site Content is strictly prohibited. Such license is subject to these Terms of Use and does not include use of any data mining, robots or similar data gathering or extraction methods. Any use of the Site or the Site Content other than as specifically authorized herein, without the prior written permission of Company, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time without notice and with or without cause.</p>
</li>
<li><b>Member Conduct</b><br />
    <p>You understand that all information, data, text, software, music, sound, photographs, graphics, video, messages or other materials ("Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you, and not UnLtdWorld, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available via the Service. UnLtdWorld has limited control of the Content posted via the Service and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Service, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will UnLtdWorld be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Service.</p>

    <p>UnLtd is not responsible for any transactions (such as direct donations to projects) occurring through the site via the service - you, and not UnLtdWorld, are entirely responsible for such transactions. The company only guarantees, and always within the conditions of the TOS, for the efficiency of the service, and is in no way responsible for content posted on the site by users and the validity of information shared between users.
You represent, warrant and agree that no materials of any kind submitted through your account or otherwise posted, transmitted, or shared by you on or through the Service will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libellous, defamatory or otherwise unlawful material.</p>

    <p>In addition, you agree to not use the Service to:</p>
    <ol>
        <li>upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, pornographic, defamatory, vulgar, obscene, libellous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</li>
        <li>harm other members in any way;</li>

        <li>impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
        <li>forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service;</li>
        <li>upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
        <li>upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights ("Rights") of any party;</li>
        <li>upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;</li>
        <li>upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>

        <li>interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;</li>
        <li>intentionally or unintentionally violate any applicable local, state, national or international law;</li>
        <li>"stalk" or otherwise harass another; or</li>
        <li>collect or store personal data about other users.</li>
    </ol>
    <p>You acknowledge that UnLtdWorld may not pre-screen Content, but that UnLtdWorld and its designees shall have the right (but not the obligation) in their sole discretion to refuse or move any Content that is available via the Service. Without limiting the foregoing, UnLtd and its designees shall have the right to remove any Content that violates these Terms of Service or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content created by UnLtdWorld or submitted to UnLtdWorld.</p>

    <p>You acknowledge and agree that UnLtdWorld may preserve Content and may also disclose Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce these terms of service; (c) respond to claims that any Content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of UnLtdWorld, our members and the public.</p>
</li>
<li><b>User Content Posted on the Site</b><br />
    <p>You are solely responsible for the photos, profiles, messages, notes, text, information, music, video, advertisements, listings, and other content that you upload, publish or display (hereinafter, "post") on or through the Service or the Site, or transmit to or share with other users (collectively the "User Content"). You may not post, transmit, or share User Content on the Site or Service that you did not create or that you do not have permission to post. You understand and agree that the Company may, but is not obligated to, review the Site and may delete or remove (without notice) any Site Content or User Content in its sole discretion, for any reason or no reason, including without limitation User Content that in the sole judgment of the Company violates this Agreement, or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of users or others. You are solely responsible at your sole cost and expense for creating backup copies and replacing any User Content you post or store on the Site or provide to the Company.</p>

    <p>When you post User Content to the Site, you authorize and direct us to make such copies thereof as we deem necessary in order to facilitate the posting and storage of the User Content on the Site. By posting User Content to any part of the Site, you automatically grant, and you represent and warrant that you have the right to grant, to the Company an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content for any purpose on or in connection with the Site or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses of the foregoing. You may remove your User Content from the Site at any time. If you choose to remove your User Content, the license granted above will automatically expire, however you acknowledge that the Company may retain archived copies of your User Content.</p>
</li>
<li><b>International Use</b><br />
    <p>Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content.</p>

</li>
<li><b>Materials submitted or made available for inclusion on the service</b><br />
    <p>UnLtdWorld does not claim ownership of Content you submit or make available for inclusion on the Service. However, with respect to Content you submit or make available for inclusion on publicly accessible areas of the Service, you grant UnLtdWorld the following world-wide, royalty free and non-exclusive license, as applicable:</p>
    <ul>
        <li>With respect to Content (including photos, graphics, audio or video) you submit or make available for inclusion on publicly accessible areas of the Service, the perpetual, irrevocable and fully sublicensable license to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and publicly display such Content (in whole or in part) and to incorporate such Content into other works in any format or medium now known or later developed.</li>
        <li>With respect to Data, the use of Data and Statistical Information, in respect of governing laws, regulations and privacy policy, gathered and logged through usage of the site and services, in order to improve and enhance such services and the site.</li>
    </ul>
    <p>We respect the intellectual property rights of others and we prohibit users from uploading, posting or otherwise transmitting on the UnLtdWorld website or service any materials that violate another party's intellectual property rights. When we receive proper Notification of Alleged Copyright Infringement, we promptly remove or disable access to the allegedly infringing material and terminate the accounts of repeat. If you believe that any material on the Site infringes upon any copyright which you own or control, you may send a written notification of such infringement to our Designated Agent.</p>

</li>
<li><b>User Disputes</b><br />
    <p>You are solely responsible for your interactions with other UnLtdWorld users. We reserve the right, but have no obligation, to monitor disputes between you and other users. For any dispute please contact us at info@unltdworld.com </p>
</li>
<li><b>Privacy</b><br />
    <p>We care about the privacy of our users. Click <a href="http://unltdworld.com/pages/privacy.php">here</a>to view the UnLtdWorld Privacy Policy. By using the Site or the Service, you are consenting to have your personal data transferred to and processed in the United Kingdom.</p>
</li>
<li><b>Disclaimers</b><br />
    <p>The Company is not responsible or liable in any manner for any User Content or Third Party Applications, Software or Content posted on the Site or in connection with the Service, whether posted or caused by users of the Site, by UnLtdWorld, by third parties or by any of the equipment or programming associated with or utilized in the Site or the Service. Although we provide rules for user conduct and postings, we do not control and are not responsible for what users post, transmit or share on the Site and are not responsible for any offensive, inappropriate, obscene, unlawful or otherwise objectionable content you may encounter on the Site or in connection with any User Content or Third Party Applications, Software or Content. The Company is not responsible for the conduct, whether online or offline, of any user of the Site or Service.</p>

    <p>The Site and the Service may be temporarily unavailable from time to time for maintenance or other reasons. Company assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User communications. The Company is not responsible for any technical malfunction or other problems of any telephone network or service, computer systems, servers or providers, computer or mobile phone equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any Site or combination thereof, including injury or damage to User's or to any other person's computer, mobile phone, or other hardware or software, related to or resulting from using or downloading materials in connection with the Web and/or in connection with the Service. Under no circumstances will the Company be responsible for any loss or damage, including any loss or damage to any User Content or personal injury or death, resulting from anyone's use of the Site or the Service, any User Content or Third Party Applications, Software or Content posted on or through the Site or the Service or transmitted to Users, or any interactions between users of the Site, whether online or offline.</p>
</li>
<li><b>Indemnity</b><br />
    <p>You agree to indemnify and hold UnLtdWorld, and its affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Content you submit, post, transmit or make available through the Service, your use of the Service, your connection to the Service, your violation of these terms of service, or your violation of any rights of another.</p>
</li>
<li><b>Links</b><br />
    <p>The Service may provide, or third parties may provide, links to other World Wide Web sites or resources. Because UnLtdWorld has no control over such sites and resources, you acknowledge and agree that UnLtdWorld is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that UnLtdWorld shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.</p>
</li>

<li><b>General Information</b><br />
    <p>These Terms of Service constitute the entire agreement between you and UnLtdWorld, and govern your use of the Service. You also may be subject to additional terms and conditions that may apply when you use affiliate services, third-party content or third-party software. The TOS and the relationship between you and UnLtdWorld shall be governed by the laws of England and Wales. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
    <p>The section titles in the TOS are for convenience only and have no legal or contractual effect.</p>
</li>
<li><b>Termination</b><br />
    <p>You agree that UnLtdWorld, in its sole discretion, may terminate your password, account (or any part thereof) or use of the Service, including without limitation if it believes that you are under 13, and remove and discard any Content within the Service, for any reason, including, without limitation, for lack of use or if UnLtdWorld believes that you have violated or acted inconsistently with the letter or spirit of the TOS. UnLtdWorld may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. You agree that any termination of your access to the Service under any provision of this TOS may be effected without prior notice, and acknowledge and agree that UnLtdWorld may immediately deactivate or delete your account and all related information in your account and/or bar any further access to the Service. Further, you agree that UnLtdWorld shall not be liable to you or any third-party for any termination of your access to the Service.</p>
    <p>At any time, you can terminate your account which will remove your profile and other personal information from view. To cancel your account contact us at info@unltdworld.com.</p>

</li>
<li><b>DISCLAIMER OF WARRANTIES</b><br />
    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</p>
    <ol>
        <li>YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. UnLtdWorld EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</li>
        <li>UnLtdWorld MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.</li>
        <li>ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</li>

        <li>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM UnLtdWorld OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.</li>
    </ol>
<li><b>LIMITATION OF LIABILITY</b><br />
    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT UnLtdWorld SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF UnLtdWorld HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
</li>
<li><b>Violations</b><br />
    <p>Please report any violations of the TOS to:</p>
</li>

<li><b>Third Party Websites, Applications and Content</b><br />
    <p>The Site contains (or you may be sent through the Site or the Service) links to other web sites ("Third Party Sites") as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software and other content or items belonging to or originating from third parties (the "Third Party Applications, Software or Content"). Such Third Party Sites and Third Party Applications, Software or Content are not investigated, monitored or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third Party Sites accessed through the Site or any Third Party Applications, Software or Content posted on, available through or installed from the Site, including without limitation the content, accuracy, offensiveness, opinions, reliability, privacy practices or other policies of or contained in the Third Party Sites or the Third Party Applications, Software or Content. Inclusion of, linking to or permitting the use or installation of any Third Party Site or any Third Party Applications, Software or Content does not imply approval or endorsement thereof by us. If you decide to leave the Site and access the Third Party Sites or to use or install any Third Party Applications, Software or Content, you do so at your own risk and you should be aware that our terms and policies no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Site or relating to any applications you use or install from the site.</p>
    <p>Several applications on UnLtdWorld are or will be developed by third-parties through a set of APIs and services provided by UnLtd that enable third-party developers to create websites and applications that retrieve authorized data made available by UnLtdWorld and its users and/or that retrieve authorized data from third-party sites for use on UnLtdWorld.</p> 

    <p>All third party developers do so in accordance with the terms and conditions set forth in an agreement entered into between UnLtd and the developers. Whilst we guarantee that we have taken all the necessary steps to ensure that these developers will only display and use your information in accordance with our terms of service, ALL USE OF THE APPLICATIONS DEVELOPED BY THIRD PARTIES IS PROVIDED "AS IS" AND AT YOUR OWN RISK. Third party developers are required to agree to restrictions on access, storage and use of such information as conditional to partnering with UnLtd. However, while we have undertaken contractual and technical steps to restrict possible misuse of such information by such developers, we do not screen or approve developers, and we cannot and do not guarantee that all developers will abide by such restrictions and agreements.</p>
    <p>Please report any suspected misuse of information through the site by third party developers to: info@unltdworld.com</p>

    <p>Developers may require you to agree to their own terms of service, privacy policies and/or other policies as a condition of using their applications.</p>

</li>
<li><b>Miscellaneous</b><br />
    <p>These Terms of Service will be governed by and construed in accordance with the laws of England and Wales, without giving effect to its conflict of laws provisions or your actual state or country of residence. The parties agree to submit to the personal and exclusive jurisdiction of the courts located in the City of London, England. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms of Service to be unenforceable, the remainder of the Terms of Service will continue in full force and effect. You shall not assign these Terms of Service or assign any rights or delegate any obligations hereunder, in whole or in part, whether voluntarily or by operation of law, without our prior written consent. Any such purported assignment or delegation will be null and void and of no force or effect.</p>
    <p>Without limiting the foregoing, under no circumstances shall the company be held liable for any delay or failure in performance resulting directly or indirectly from acts of nature, forces, or causes beyond its reasonable control.  Including, without limitation, Internet failures, computer equipment failures, telecommunication equipment failures, other equipment failures, electrical power failures, strikes, labour disputes, riots, insurrections, civil disturbances, shortages of labour or materials, fires, floods, storms, explosions, acts of God, war, governmental actions, orders of domestic or foreign courts or tribunals, non-performance of third parties, or loss of or fluctuations in heat, light, or air conditioning.</p>
    <p>These Terms of Service constitute the entire agreement between you and UnLtd with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. Any waiver of any provision of the Terms of Service by a party will be effective only if in writing and signed by a party.</p>
</li>
<li>
<b>Contact Details</b>:<br />
<p>UnLtdWorld - C/O UnLtd - 123 Whitecross Street - EC1Y 8JJ London<br> 
T: +44 020 7566 1100 E: info@unltdworld.com<br>
UnLtd is a registered charity, number 1090393 and our company registration number is 4180639.</p>
</li>
</ol>
</div>