apiVersion: apps/v1
kind: Deployment
metadata:
  name: elgg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elgg-app
  template:
    metadata:
      labels:
        app: elgg-app
    spec:
      initContainers:
      - name: fix-permissions
        image: bitaouioussama/elgg-app:v6
        command: ["/bin/sh", "-c", "chown -R www-data:www-data /var/elgg_data && chmod -R 775 /var/elgg_data"]
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data

      containers:
      - name: elgg-app
        image: bitaouioussama/elgg-app:v6
        envFrom:
          - secretRef:
              name: elgg-env
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "384Mi"
        volumeMounts:
        - mountPath: /var/elgg_data
          name: elgg-data

      volumes:
      - name: elgg-data
        persistentVolumeClaim:
          claimName: elgg-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: elgg-app
spec:
  type: LoadBalancer
  selector:
    app: elgg-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 34.22.137.184
