apiVersion: apps/v1
kind: Deployment
metadata:
  name: elgg-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elgg-phpmyadmin
  template:
    metadata:
      labels:
        app: elgg-phpmyadmin
    spec:
      nodeSelector:
        kubernetes.io/hostname: gke-elgg-cluster-default-pool-613e100a-jnqh
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        envFrom:
          - secretRef:
              name: elgg-env
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: elgg-phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: elgg-phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
<<<<<<< HEAD
  loadBalancerIP: 34.175.63.179
=======
  loadBalancerIP: 34.175.63.179
>>>>>>> 413930836491fa59c1d3c78d649f6cf633daf9dd
