name: "Feature request"
description: "Are you missing a feature? Please suggest how we can improve Elgg."
title: "[Feature]: "
labels: "feature"
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is."
      value: "I'm always frustrated when [...]"
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
