// ES lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Citaci&oacute;n',
abbr_desc : 'Abreviatura',
acronym_desc : 'Acr&oacute;nimo',
del_desc : 'Borrado',
ins_desc : 'Inserci&oacute;n',
attribute_label_title : 'T&iacute;tulo',
attribute_label_id : 'ID',
attribute_label_class : 'Clase',
attribute_label_style : 'Estilo',
attribute_label_cite : 'Cita',
attribute_label_datetime : 'Fecha/Hora',
attribute_label_langdir : 'Direcci&oacute;n del texto',
attribute_option_ltr : 'De izquierda a derecha',
attribute_option_rtl : 'De derecha a izquierda',
attribute_label_langcode : 'Idioma',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'AccessKey',
attribute_label_cite : 'Cita',
attribute_events_tab : 'Eventos',
attribute_attrib_tab : 'Atributos',
general_tab : 'General',
attrib_tab : 'Atributos',
events_tab : 'Eventos',
fieldset_general_tab : 'Configuraci&oacute;n General',
fieldset_attrib_tab : 'Atributos de Elemento',
fieldset_events_tab : 'Eventos de Elemento',
title_ins_element : 'Inserci&oacute;n de Elemento',
title_del_element : 'Borrado de Elemento',
title_acronym_element : 'Elemento Acr&oacute;nimo',
title_abbr_element : 'Elemento Abreviatura',
title_cite_element : 'Elemento Cita',
remove : 'Eliminar',
not_set : '--no establecido--',
insert_date : 'Insertar fecha/hora actual',
option_ltr : 'De izquierda a derecha',
option_rtl : 'De derecha a izquierda',
attribs_desc : 'Insertar/Editar Atributos',
attribs_title : 'Insertar/Editar Atributos'
});
