// FR lang variables
// Modified by shadow walker, last updated 2007-03-16

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Citation',
abbr_desc : 'Abr&eacute;viation',
acronym_desc : 'Acronyme',
del_desc : 'Effacer',
ins_desc : 'Insertion',
attribute_label_title : 'Titre',
attribute_label_id : 'ID',
attribute_label_class : 'Classe',
attribute_label_style : 'Style',
attribute_label_cite : 'Cite',
attribute_label_datetime : 'Date/Heure',
attribute_label_langdir : 'Text Direction',
attribute_option_ltr : 'De gauche &agrave; droite',
attribute_option_rtl : 'De droite &agrave; gauche',
attribute_label_langcode : 'Langues',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'AccessKey',
attribute_label_cite : 'Cite',
attribute_events_tab : 'Evenement',
attribute_attrib_tab : 'Attribus',
general_tab : 'G&eacute;n&eacute;rale',
attrib_tab : 'Attribus',
events_tab : 'Evenement',
fieldset_general_tab : 'General Settings',
fieldset_attrib_tab : 'Attributs de l\'&eacute;l&eacute;ment',
fieldset_events_tab : 'Element Events',
title_ins_element : 'Insertion de l\'&eacute;l&eacute;ment',
title_del_element : 'Effacement de l\'&eacute;l&eacute;ment',
title_acronym_element : 'Acronyme de l\'&eacute;l&eacute;ment',
title_abbr_element : 'Abr&eacute;viation de l\'&eacute;l&eacute;ment',
title_cite_element : 'Citation Element',
remove : 'Enlever',
not_set : '--Non d&eacute;finit--',
insert_date : 'Ins&eacute;rer la date/heure actuelle',
option_ltr : 'De gauche &agrave; droite',
option_rtl : 'De droite &agrave; gauche',
attribs_desc : 'Ins&eacute;rer/Editer un attribut',
attribs_title : 'Ins&eacute;rer/Editer un attribut'
});
