// UK lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Цитування',
abbr_desc : 'Абревіатура',
acronym_desc : 'Акронім',
del_desc : 'Стирання',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ID',
attribute_label_class : 'Клас',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Цитувати',
attribute_label_datetime : 'Дата/Час',
attribute_label_langdir : 'Напрямок Тексту',
attribute_option_ltr : 'Зліва направо',
attribute_option_rtl : 'Справа наліво',
attribute_label_langcode : 'Мова',
attribute_label_tabindex : 'Порядковий Номер',
attribute_label_accesskey : 'Гаряча Клавіша',
attribute_label_cite : 'Цитувати',
attribute_events_tab : 'Події',
attribute_attrib_tab : 'Атрибути',
general_tab : 'Основний',
attrib_tab : 'Атрибути',
events_tab : 'Події',
fieldset_general_tab : 'Основні Установки',
fieldset_attrib_tab : 'Елемент Атрибути',
fieldset_events_tab : 'Елемент Події',
title_ins_element : 'Елемент Вставка',
title_del_element : 'Елемент Події',
title_acronym_element : 'Елемент Акронім',
title_abbr_element : 'Елемент Абревіатура',
title_cite_element : 'Елемент Цитування',
remove : 'Прибрати',
not_set : '--не встановлено--',
insert_date : 'Вставити поточні дату/час',
option_ltr : 'Зліва направо',
option_rtl : 'Справа наліво',
attribs_desc : 'Вставити/Змінити Атрибути',
attribs_title : 'Вставити/Змінити Атрибути'
});
