// UK lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Цитування',
abbr_desc : 'Абрев╕атура',
acronym_desc : 'Акрон╕м',
del_desc : 'Стирання',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ID',
attribute_label_class : 'Клас',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Цитувати',
attribute_label_datetime : 'Дата/Час',
attribute_label_langdir : 'Напрямок Тексту',
attribute_option_ltr : 'Зл╕ва направо',
attribute_option_rtl : 'Справа нал╕во',
attribute_label_langcode : 'Мова',
attribute_label_tabindex : 'Порядковий Номер',
attribute_label_accesskey : 'Гаряча Клав╕ша',
attribute_label_cite : 'Цитувати',
attribute_events_tab : 'Под╕╖',
attribute_attrib_tab : 'Атрибути',
general_tab : 'Основний',
attrib_tab : 'Атрибути',
events_tab : 'Под╕╖',
fieldset_general_tab : 'Основн╕ Установки',
fieldset_attrib_tab : 'Елемент Атрибути',
fieldset_events_tab : 'Елемент Под╕╖',
title_ins_element : 'Елемент Вставка',
title_del_element : 'Елемент Под╕╖',
title_acronym_element : 'Елемент Акрон╕м',
title_abbr_element : 'Елемент Абрев╕атура',
title_cite_element : 'Елемент Цитування',
remove : 'Прибрати',
not_set : '--не встановлено--',
insert_date : 'Вставити поточн╕ дату/час',
option_ltr : 'Зл╕ва направо',
option_rtl : 'Справа нал╕во',
attribs_desc : 'Вставити/Зм╕нити Атрибути',
attribs_title : 'Вставити/Зм╕нити Атрибути'
});
