<?php

namespace Elgg\Icons;

/**
 * Adds FontAwesome icon classes
 *
 * @since 4.3
 */
class AddFontAwesomeClassesHandler {
	
	/**
	 * Common alternative spelling for icons in Elgg
	 *
	 * @var array
	 */
	public const array COMMON_ICONS = [
		'delete-alt' => 'circle-xmark',
		'delete' => 'xmark',
		'grid' => 'table-cells',
		'info' => 'info-circle',
		'mail' => 'envelope-regular',
		'refresh' => 'arrow-rotate-right',
		'remove' => 'times',
		'settings' => 'wrench',
		'settings-alt' => 'gear',
	];
	
	/**
	 * FontAwesome brand icons
	 *
	 * @var array
	 */
	public const array BRANDS = [
		'42-group',
		'500px',
		'accessible-icon',
		'accusoft',
		'adn',
		'adversal',
		'affiliatetheme',
		'airbnb',
		'algolia',
		'alipay',
		'amazon',
		'amazon-pay',
		'amilia',
		'android',
		'angellist',
		'angrycreative',
		'angular',
		'app-store',
		'app-store-ios',
		'apper',
		'apple',
		'apple-pay',
		'artstation',
		'asymmetrik',
		'atlassian',
		'audible',
		'autoprefixer',
		'avianex',
		'aviato',
		'aws',
		'bandcamp',
		'battle-net',
		'behance',
		'bilibili',
		'bimobject',
		'bitbucket',
		'bitcoin',
		'bity',
		'black-tie',
		'blackberry',
		'blogger',
		'blogger-b',
		'bluesky',
		'bluetooth',
		'bluetooth-b',
		'bootstrap',
		'bots',
		'brave',
		'brave-reverse',
		'btc',
		'buffer',
		'buromobelexperte',
		'buy-n-large',
		'buysellads',
		'canadian-maple-leaf',
		'cash-app',
		'cc-amazon-pay',
		'cc-amex',
		'cc-apple-pay',
		'cc-diners-club',
		'cc-discover',
		'cc-jcb',
		'cc-mastercard',
		'cc-paypal',
		'cc-stripe',
		'cc-visa',
		'centercode',
		'centos',
		'chrome',
		'chromecast',
		'cloudflare',
		'cloudscale',
		'cloudsmith',
		'cloudversify',
		'cmplid',
		'codepen',
		'codiepie',
		'confluence',
		'connectdevelop',
		'contao',
		'cotton-bureau',
		'cpanel',
		'creative-commons',
		'creative-commons-by',
		'creative-commons-nc',
		'creative-commons-nc-eu',
		'creative-commons-nc-jp',
		'creative-commons-nd',
		'creative-commons-pd',
		'creative-commons-pd-alt',
		'creative-commons-remix',
		'creative-commons-sa',
		'creative-commons-sampling',
		'creative-commons-sampling-plus',
		'creative-commons-share',
		'creative-commons-zero',
		'critical-role',
		'css',
		'css3',
		'css3-alt',
		'cuttlefish',
		'd-and-d',
		'd-and-d-beyond',
		'dailymotion',
		'dart-lang',
		'dashcube',
		'debian',
		'deezer',
		'delicious',
		'deploydog',
		'deskpro',
		'dev',
		'deviantart',
		'dhl',
		'diaspora',
		'digg',
		'digital-ocean',
		'discord',
		'discourse',
		'disqus',
		'dochub',
		'docker',
		'draft2digital',
		'dribbble',
		'dropbox',
		'drupal',
		'duolingo',
		'dyalog',
		'earlybirds',
		'ebay',
		'edge',
		'edge-legacy',
		'elementor',
		'eleventy',
		'ello',
		'ember',
		'empire',
		'envira',
		'erlang',
		'ethereum',
		'etsy',
		'evernote',
		'expeditedssl',
		'facebook',
		'facebook-f',
		'facebook-messenger',
		'fantasy-flight-games',
		'fedex',
		'fedora',
		'figma',
		'files-pinwheel',
		'firefox',
		'firefox-browser',
		'first-order',
		'first-order-alt',
		'firstdraft',
		'flickr',
		'flipboard',
		'flutter',
		'fly',
		'font-awesome',
		'fonticons',
		'fonticons-fi',
		'fort-awesome',
		'fort-awesome-alt',
		'forumbee',
		'foursquare',
		'free-code-camp',
		'freebsd',
		'fulcrum',
		'galactic-republic',
		'galactic-senate',
		'get-pocket',
		'gg',
		'gg-circle',
		'git',
		'git-alt',
		'github',
		'github-alt',
		'gitkraken',
		'gitlab',
		'gitter',
		'glide',
		'glide-g',
		'gofore',
		'golang',
		'goodreads',
		'goodreads-g',
		'google',
		'google-drive',
		'google-pay',
		'google-play',
		'google-plus',
		'google-plus-g',
		'google-scholar',
		'google-wallet',
		'gratipay',
		'grav',
		'gripfire',
		'grunt',
		'guilded',
		'gulp',
		'hacker-news',
		'hackerrank',
		'hashnode',
		'hips',
		'hire-a-helper',
		'hive',
		'hooli',
		'hornbill',
		'hotjar',
		'houzz',
		'html5',
		'hubspot',
		'ideal',
		'imdb',
		'instagram',
		'instalod',
		'intercom',
		'internet-explorer',
		'invision',
		'ioxhost',
		'itch-io',
		'itunes',
		'itunes-note',
		'java',
		'jedi-order',
		'jenkins',
		'jira',
		'joget',
		'joomla',
		'js',
		'jsfiddle',
		'jxl',
		'kaggle',
		'kakao-talk',
		'keybase',
		'keycdn',
		'kickstarter',
		'kickstarter-k',
		'korvue',
		'laravel',
		'lastfm',
		'leanpub',
		'less',
		'letterboxd',
		'line',
		'linkedin',
		'linkedin-in',
		'linktree',
		'linode',
		'linux',
		'lumon',
		'lumon-drop',
		'lyft',
		'magento',
		'mailchimp',
		'mandalorian',
		'markdown',
		'mastodon',
		'maxcdn',
		'mdb',
		'medapps',
		'medium',
		'medrt',
		'meetup',
		'megaport',
		'mendeley',
		'meta',
		'microblog',
		'microsoft',
		'mintbit',
		'mix',
		'mixcloud',
		'mixer',
		'mizuni',
		'modx',
		'monero',
		'napster',
		'neos',
		'nfc-directional',
		'nfc-symbol',
		'nimblr',
		'node',
		'node-js',
		'notion',
		'npm',
		'ns8',
		'nutritionix',
		'octopus-deploy',
		'odnoklassniki',
		'odysee',
		'old-republic',
		'openai',
		'opencart',
		'openid',
		'opensuse',
		'opera',
		'optin-monster',
		'orcid',
		'osi',
		'padlet',
		'page4',
		'pagelines',
		'palfed',
		'pandora',
		'patreon',
		'paypal',
		'perbyte',
		'periscope',
		'phabricator',
		'phoenix-framework',
		'phoenix-squadron',
		'php',
		'pied-piper',
		'pied-piper-alt',
		'pied-piper-hat',
		'pied-piper-pp',
		'pinterest',
		'pinterest-p',
		'pix',
		'pixelfed',
		'pixiv',
		'playstation',
		'product-hunt',
		'pushed',
		'python',
		'qq',
		'quinscape',
		'quora',
		'r-project',
		'raspberry-pi',
		'ravelry',
		'react',
		'reacteurope',
		'readme',
		'rebel',
		'red-river',
		'reddit',
		'reddit-alien',
		'redhat',
		'renren',
		'replyd',
		'researchgate',
		'resolving',
		'rev',
		'rocketchat',
		'rockrms',
		'rust',
		'safari',
		'salesforce',
		'sass',
		'schlix',
		'screenpal',
		'scribd',
		'searchengin',
		'sellcast',
		'sellsy',
		'servicestack',
		'shirtsinbulk',
		'shoelace',
		'shopify',
		'shopware',
		'signal-messenger',
		'simplybuilt',
		'sistrix',
		'sith',
		'sitrox',
		'sketch',
		'skyatlas',
		'skype',
		'slack',
		'slideshare',
		'snapchat',
		'soundcloud',
		'sourcetree',
		'space-awesome',
		'speakap',
		'speaker-deck',
		'spotify',
		'square-behance',
		'square-bluesky',
		'square-dribbble',
		'square-facebook',
		'square-figma',
		'square-font-awesome',
		'square-font-awesome-stroke',
		'square-git',
		'square-github',
		'square-gitlab',
		'square-google-plus',
		'square-hacker-news',
		'square-instagram',
		'square-js',
		'square-lastfm',
		'square-letterboxd',
		'square-linkedin',
		'square-odnoklassniki',
		'square-pied-piper',
		'square-pinterest',
		'square-reddit',
		'square-snapchat',
		'square-steam',
		'square-threads',
		'square-tumblr',
		'square-twitter',
		'square-upwork',
		'square-viadeo',
		'square-vimeo',
		'square-web-awesome',
		'square-web-awesome-stroke',
		'square-whatsapp',
		'square-x-twitter',
		'square-xing',
		'square-youtube',
		'squarespace',
		'stack-exchange',
		'stack-overflow',
		'stackpath',
		'staylinked',
		'steam',
		'steam-symbol',
		'sticker-mule',
		'strava',
		'stripe',
		'stripe-s',
		'stubber',
		'studiovinari',
		'stumbleupon',
		'stumbleupon-circle',
		'superpowers',
		'supple',
		'suse',
		'swift',
		'symfony',
		'teamspeak',
		'telegram',
		'tencent-weibo',
		'tex',
		'the-red-yeti',
		'themeco',
		'themeisle',
		'think-peaks',
		'threads',
		'tidal',
		'tiktok',
		'trade-federation',
		'trello',
		'tumblr',
		'twitch',
		'twitter',
		'typo3',
		'uber',
		'ubuntu',
		'uikit',
		'umbraco',
		'uncharted',
		'uniregistry',
		'unity',
		'unsplash',
		'untappd',
		'ups',
		'upwork',
		'usb',
		'usps',
		'ussunnah',
		'vaadin',
		'viacoin',
		'viadeo',
		'viber',
		'vimeo',
		'vimeo-v',
		'vine',
		'vk',
		'vnv',
		'vsco',
		'vuejs',
		'w3c',
		'watchman-monitoring',
		'waze',
		'web-awesome',
		'webflow',
		'weebly',
		'weibo',
		'weixin',
		'whatsapp',
		'whmcs',
		'wikipedia-w',
		'windows',
		'wirsindhandwerk',
		'wix',
		'wizards-of-the-coast',
		'wodu',
		'wolf-pack-battalion',
		'wordpress',
		'wordpress-simple',
		'wpbeginner',
		'wpexplorer',
		'wpforms',
		'wpressr',
		'x-twitter',
		'xbox',
		'xing',
		'y-combinator',
		'yahoo',
		'yammer',
		'yandex',
		'yandex-international',
		'yarn',
		'yelp',
		'yoast',
		'youtube',
		'zhihu',
	];
	
	/**
	 * Converts icon classes to correct FontAwesome classes
	 *
	 * @param \Elgg\Event $event 'view_vars', 'output/icon'
	 *
	 * @return array
	 */
	public function __invoke(\Elgg\Event $event) {
		$vars = $event->getValue();
		
		$classes = elgg_extract_class($vars);
		
		foreach ($classes as $icon_class) {
			if (!preg_match_all('/^elgg-icon-(.+)/i', $icon_class)) {
				continue;
			}
			
			// strip elgg-icon-
			$base_icon = preg_replace('/^elgg-icon-(.+)/i', '$1', $icon_class);
			
			// convert common icons
			$base_icon = elgg_extract($base_icon, self::COMMON_ICONS, $base_icon);
			
			// map solid/regular/light/thin iconnames to correct classes
			if (preg_match('/.*-solid$/', $base_icon)) {
				$base_icon = preg_replace('/(.*)-solid$/', '$1', $base_icon);
				$classes[] = 'fa-solid';
			} elseif (preg_match('/.*-regular$/', $base_icon)) {
				$base_icon = preg_replace('/(.*)-regular$/', '$1', $base_icon);
				$classes[] = 'fa-regular';
			} elseif (preg_match('/.*-light$/', $base_icon)) {
				// currently light is only available in FontAwesome 7 Pro
				$base_icon = preg_replace('/(.*)-light$/', '$1', $base_icon);
				$classes[] = 'fa-light';
			} elseif (preg_match('/.*-thin$/', $base_icon)) {
				// currently thin is only available in FontAwesome 7 Pro
				$base_icon = preg_replace('/(.*)-thin$/', '$1', $base_icon);
				$classes[] = 'fa-thin';
			} elseif (in_array($base_icon, self::BRANDS)) {
				$classes[] = 'fa-brands';
			} else {
				$classes[] = 'fa-solid';
			}
	
			$classes[] = "fa-{$base_icon}";
		}

		$vars['class'] = array_unique($classes);
	
		return $vars;
	}
}
