// UK lang variables

tinyMCE.addToLang('media',{
title : 'Lis&auml;&auml; / muokkaa upotettua mediaa',
desc : 'Lis&auml;&auml; / muokkaa upotettua mediaa',
general : 'Yleiset',
advanced : 'Edistyneet',
file : 'Tiedosto',
list : 'Lista',
size : 'Koko',
preview : 'Esikatselu',
constrain_proportions : 'S&auml;ilyt&auml; kuvasuhde',
type : 'Tyyppi',
id : 'Id',
name : 'Nimi',
class_name : 'Luokka',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Toista automaattisesti',
loop : 'Toista loputtomasti',
menu : 'Näytä valikko',
quality : 'Laatu',
scale : 'Skaalaus',
align : 'Asettelu',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Taustaväri',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Välimuisti',
hidden : 'Piilotettu',
controller : 'Controller',
kioskmode : 'Kioski moodi',
playeveryframe : 'Toista jokainen kuva',
targetcache : 'Kohdevälimuisti',
correction : 'Ei korjausta',
enablejavascript : 'Salli JavaScript',
starttime : 'Aloitusaika',
endtime : 'Lopetusaika',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Kohde',
volume : 'Äänen voimakkuus',
autostart : 'Toista automaattisesti',
enabled : 'Aktivoitu',
fullscreen : 'Kokoruutu',
invokeurls : 'Invoke URLs',
mute : 'Mykistä',
stretchtofit : 'Venytä sopivaksi',
windowlessvideo : 'Ikkunaton video',
balance : 'Balanssi',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Current marker',
currentposition : 'Current position',
defaultframe : 'Default frame',
playcount : 'Toiston lukumäärä',
rate : 'Nopeus',
uimode : 'UI Moodi',
flash_options : 'Flash asetukset',
qt_options : 'Quicktime asetukset',
wmp_options : 'Windows media player asetukset',
rmp_options : 'Real media player asetukset',
shockwave_options : 'Shockwave asetukset',
autogotourl : 'Auto goto URL',
center : 'Keskitetty',
imagestatus : 'Kuvan tila',
maintainaspect : 'Säilytä kuvasuhde',
nojava : 'Ei Javaa',
prefetch : 'Prefetch',
shuffle : 'Sekoitettu järjestys',
console : 'Console',
numloop : 'Toiston lukumäärä',
controls : 'Kontrollit',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Ääni',
progress : 'Edistyminen',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..'
});
