/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('media',{
title : 'Inserir / editar midia incorporada',
desc : 'Inserir / editar midia incorporada',
general : 'Geral',
advanced : 'Avan&ccedil;ado',
file : 'Arquivo',
list : 'Lista',
size : 'Dimens&otilde;es',
preview : 'Preview',
constrain_proportions : 'Confinar propor&ccedil;&otilde;es',
type : 'Tipo',
id : 'Id',
name : 'Nome',
class_name : 'Classe',
vspace : 'Espa&ccedil;o-V',
hspace : 'Espa&ccedil;o-H',
play : 'Tocar automaticamente',
loop : 'Loop',
menu : 'Mostrar menu',
quality : 'Qualidade',
scale : 'Escala',
align : 'Alinhamento',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Fundo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Escondido',
controller : 'Controlador',
kioskmode : 'Modo Kiosk',
playeveryframe : 'Tocar cada frame',
targetcache : 'Destino do cache',
correction : 'Sem corre&ccedil;&atilde;o',
enablejavascript : 'Ativar JavaScript',
starttime : 'Tempo de in&iacute;cio',
endtime : 'Tempo de fim',
href : 'Href',
qtsrcchokespeed : 'Velocidade do bloqueador',
target : 'Destino',
volume : 'Volume',
autostart : 'In&iacute;cio autom&aacute;tico',
enabled : 'Ativado',
fullscreen : 'Tela Cheia',
invokeurls : 'Chamar URLs',
mute : 'Silencioso',
stretchtofit : 'Esticar para caber',
windowlessvideo : 'V&iacute;deo em janela',
balance : 'Balan&ccedil;o',
baseurl : 'URL Base',
captioningid : 'Id de identifica&ccedil;&atilde;o',
currentmarker : 'Marcador Atual',
currentposition : 'Posi&ccedil;&atilde;o Atual',
defaultframe : 'Frame padr&atilde;o',
playcount : 'Contador',
rate : 'Taxa',
uimode : 'Modo UI',
flash_options : 'Op&ccedil;&otilde;es do Flash',
qt_options : 'Op&ccedil;&otilde;es do Quicktime',
wmp_options : 'Op&ccedil;&otilde;es do Windows media player',
rmp_options : 'Op&ccedil;&otilde;es do Real media player',
shockwave_options : 'Op&ccedil;&otilde;es do Shockwave',
autogotourl : 'Ir automaticamente para URL',
center : 'Centro',
imagestatus : 'Estatus da Imagem',
maintainaspect : 'Manter aspecto',
nojava : 'Sem java',
prefetch : 'Leitura inicial',
shuffle : 'Aleat&oacute;rio',
console : 'Console',
numloop : 'N&uacute;mero de loops',
controls : 'Controles',
scriptcallbacks : 'Script de retorno',
swstretchstyle : 'Estilo para o Stretch',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Som',
progress : 'Progresso',
qtsrc : 'QT Src',
qt_stream_warn : 'Os recursos do Streamed rtsp podem ser adicionado ao campo QT Src na aba avan&ccedil;ada.\nVoc&ecirc; pode tamb&eacute;m adicionar uma vers&atilde;o n&atilde;o streamer ao comapo Src.'
});
