<?php

	// Add multiple users
	
		if (logged_on && run("users:flags:get", array("admin", $_SESSION['userid']))) {
			
			global $admin_users_add;
			if (!isset($admin_users_add)) {
				$admin_users_add = array("", "", "", "", "", "", "", "", "", "", "", "");
			} else {
				for ($i = 0; $i < 12; $i++) {
					if (!isset($admin_users_add[$i])) {
						$admin_users_add[$i] = "";
					}
				}
			}
			
			$run_result .= "<p>" . gettext("You can create up to 12 users below; passwords will be autogenerated and emailed to the account owners. You must include all fields, but you may leave rows blank.") . "</p>";
			$run_result .= "<form action=\"\" method=\"post\">";
			
			$name = "<b>" . gettext("Username") . "</b><br /><br />";
			$column1 = "<b>" . gettext("Full name") . "</b><br /><br />";
			$column2 = "<b>" . gettext("Email address") . "</b><br /><br />";
			
			for ($i = 0; $i < 12; $i++) {
				
				$tab = (($i + 1) * 3);
				
				$name .= "<input type=\"text\" name=\"new_username[$i]\" value=\"\" tabindex=\"".($tab)."\" value=\"".htmlentities($admin_users_add[$i]->username)."\" /><br />";
				$column1 .= "<input type=\"text\" name=\"new_name[$i]\" value=\"\" tabindex=\"".($tab + 1)."\" value=\"".htmlentities($admin_users_add[$i]->name)."\" /><br />";
				$column2 .= "<input type=\"text\" name=\"new_email[$i]\" value=\"\" tabindex=\"".($tab + 2)."\" value=\"".htmlentities($admin_users_add[$i]->email)."\" /><br />";

			}	
			
			$name .= "<input type=\"hidden\" name=\"action\" value=\"admin:users:add\" />";
			$column1 .= "<br /><input type=\"submit\" value=\"" . gettext("Add users") . "\" tabindex=\"39\" />";
			
			$run_result .= run("templates:draw", array(
					'context' => 'databox',
					'name' => $name,
					'column1' => $column1,
					'column2' => $column2
				)
				);
				
				
			$run_result .= "</form>";
			
		}

?>