<?php
/**
 * Elgg user display (details)
 * @uses $vars['entity'] The user entity
 *
 * @todo this needs to recieve a list of activity or HTML in $vars that's generated by a plugin hook.
 * None of this logic should be here.
 */
$limit = 20;

if (is_plugin_enabled('thewire')) {
	// users last status msg, if they posted one
	echo elgg_view("profile/status", array("entity" => $vars['entity']));
}

if (is_plugin_enabled('conversations')) {
	// users last status msg, if they posted one
	echo elgg_view("profile/status", array("entity" => $vars['entity']));
}

if (is_plugin_enabled('riverdashboard')) {
	//select the correct river
	if (get_plugin_setting('activitytype', 'riverdashboard') == 'classic') {
		echo elgg_view_river_items($vars['entity']->getGuid(), 0, '', '', '', '', $limit,0,0,false,true);
	} else {
		echo elgg_view_river_items($vars['entity']->getGuid(), 0, '', '', '', '', $limit,0,0,false,false);
		echo elgg_view('riverdashboard/js');
	}
} else {
	// @todo this should not be here.
	echo "Riverdashboard not loaded";
}