// Initial translation by Dimitris Giannitsaros / MediSign SA

tinyMCE.addToLang('advlink',{
general_tab : 'Γενικά',
popup_tab : 'Popup',
events_tab : 'Συμβάντα',
advanced_tab : 'Για προχωρημένους',
general_props : 'Γενικές ιδιότητες',
popup_props : 'Ιδιότητες popup',
event_props : 'Συμβάντα',
advanced_props : 'Προχωρημένες ιδιότητες',
popup_opts : 'Επιλογές',
anchor_names : '’γκυρες',
target_same : '’νοιγμα στο ίδιο παράθυρο / frame',
target_parent : '’νοιγμα στο πατρικό παράθυρο / frame',
target_top : '’νοιγμα στο πάνω frame (αντικαθιστά όλα τα frames)',
target_blank : '’νοιγμα σε νέο παράθυρο',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Όνομα παραθύρου',
popup_return : 'Εισαγωγή \'return false\'',
popup_scrollbars : 'Εμφάνιση μπαρών κύλισης',
popup_statusbar : 'Εμφάνιση μπάρας κατάστασης',
popup_toolbar : 'Εμφάνιση μπαρών εργαλείων',
popup_menubar : 'Εμφάνιση μενού',
popup_location : 'Εμφάνιση μπάρας τοποθεσίας',
popup_resizable : 'Το παράθυρο να επιτρέπει αλλαγή μεγέθους',
popup_dependent : 'Εξαρτώμενο(μόνο Mozilla/Firefox)',
popup_size : 'Μέγεθος',
popup_position : 'Θέση (X/Y)',
id : 'Κωδ.',
style: 'Στυλ',
classes : 'Κλάσσεις',
target_name : 'Όνομα στόχου',
langdir : 'Διεύθυνση γλώσσας',
target_langcode : 'Γλώσσα στόχου',
langcode : 'Κωδικός γλώσσας',
encoding : 'Κωδικοποίηση γλώσσας στόχου',
mime : 'Τύπος MIME στόχου',
rel : 'Σχέση σελίδας με στόχο',
rev : 'Σχέση στόχου με σελίδα',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Αριστερά προς δεξιά',
rtl : 'Δεξιά προς αριστερά'
});
