// FI lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Yleiset',
popup_tab : 'Ponnahdusikkuna',
events_tab : 'Tapahtumat',
advanced_tab : 'Lis&auml;asetukset',
general_props : 'Yleiset asetukset',
popup_props : 'Ponnahdusikkunan asetukset',
event_props : 'Tapahtumat',
advanced_props : 'Lis&auml;asetukset',
popup_opts : 'Asetukset',
anchor_names : 'Ankkurit',
target_same : 'Avaa t&auml;ss&auml; ikkunassa / kehyksess&auml;',
target_parent : 'Avaa is&auml;nt&auml;ikkunassa / kehyksess&auml;',
target_top : 'Avaa kokoruudulle (korvaa kaikki kehykset)',
target_blank : 'Avaa uuteen ikkunaan',
popup : 'Javascript ponnahdusikkuna',
popup_url : 'Ponnahdusikkunan osoite',
popup_name : 'Ikkunan nimi',
popup_return : 'Lis&auml;&auml; \'return false\'',
popup_scrollbars : 'N&auml;yt&auml; vierityspalkit',
popup_statusbar : 'N&auml;yt&auml; tilarivi',
popup_toolbar : 'N&auml;yt&auml; ty&ouml;kalurivi',
popup_menubar : 'N&auml;yt&auml; valikkorivi',
popup_location : 'N&auml;yt&auml; sijaintipalkki',
popup_resizable : 'Kokoa voi muuttaa',
popup_dependent : 'Riippuvainen (vain Mozilla/Firefox)',
popup_size : 'Koko',
popup_position : 'Sijainti (X/Y)',
id : 'Id',
style: 'Tyyli',
classes : 'Luokat',
target_name : 'Kohteen nimi',
langdir : 'Kohteen kielen suunta',
target_langcode : 'Kohteen kieli',
langcode : 'Kielikoodi',
encoding : 'Kohteen merkkikoodisto',
mime : 'Kohteen MIME tyyppi',
rel : 'Sivun suhde kohteeseen',
rev : 'Kohteen suhde sivuun',
tabindex : 'Tabindex',
accesskey : 'Pikan&auml;pp&auml;in',
ltr : 'Vasemmalta oikealle',
rtl : 'Oikealta vasemmalle'
});
