// JA lang variables

tinyMCE.addToLang('advlink',{
general_tab : '全般',
popup_tab : 'ポップアップ',
events_tab : 'イベント',
advanced_tab : '詳細',
general_props : '全般',
popup_props : 'ポップアップ',
event_props : 'イベント',
advanced_props : '詳細',
popup_opts : 'オプション',
anchor_names : 'しおり',
target_same : '同じウィンドウで開く',
target_parent : '親ウィンドウで開く',
target_top : 'トップウィンドウで開く',
target_blank : '新しいウィンドウで開く',
popup : 'Javascriptポップアップを使用する',
popup_url : 'ＵＲＬ',
popup_name : 'ウィンドウのタイトル',
popup_return : '\'return false\'を挿入',
popup_scrollbars : 'スクロールバーを表示する',
popup_statusbar : 'ステータスバーを表示する',
popup_toolbar : 'ツールバーを表示する',
popup_menubar : 'メニューバーを表示する',
popup_location : 'アドレスバーを表示する',
popup_resizable : '大きさを変更可能なウィンドウとする',
popup_dependent : '親ウィンドウと連動する(Mozilla/Firefoxのみ)',
popup_size : '大きさ',
popup_position : '位置(X/Y)',
id : 'ＩＤ',
style: 'スタイル',
classes : 'クラス',
target_name : '表示先のウィンドウ',
langdir : '表示の方向',
target_langcode : '表示先の言語',
langcode : '言語',
encoding : '文字コード',
mime : '表示先のMIMEタイプ',
rel : 'このページから表示先への関連',
rev : '表示先からこのページへの関連',
tabindex : 'タブ順序',
accesskey : 'ショートカットキー',
ltr : '左から右へ',
rtl : '右から左へ'
});
