// 日本語 utf-8 lang variables

tinyMCE.addToLang('advlink',{
general_tab : '一般',
popup_tab : 'ポップアップ',
events_tab : 'イベント',
advanced_tab : '詳細',
general_props : '一般のプロパティ',
popup_props : 'ポップアップのプロパティ',
event_props : 'イベント',
advanced_props : '詳細のプロパティ',
popup_opts : '選択',
anchor_names : 'アンカー',
target_same : 'このウインドウで開く',
target_parent : '親ウインドウで開く',
target_top : '上のフレームで開く',
target_blank : '新ウインドウで開く',
popup : 'Javascript ポップアップ',
popup_url : 'ポップアップ URL',
popup_name : 'ウインドウ名',
popup_return : '挿入 \'return false\'',
popup_scrollbars : 'スクロールバーを表示',
popup_statusbar : 'ステータスバーを表示',
popup_toolbar : 'ツールバーを表示',
popup_menubar : 'メニューバーを表示',
popup_location : 'アドレスバーを表示',
popup_resizable : 'ウインドウを調整可にする',
popup_dependent : '頼り (Mozilla/Firefox のみ)',
popup_size : 'サイズ',
popup_position : '位置 (X/Y)',
id : 'Id',
style: 'スタイル',
classes : 'クラス',
target_name : 'ターゲット名',
langdir : '言葉の向き',
target_langcode : 'ターゲットの言葉',
langcode : '言葉のコード',
encoding : 'ターゲットの文字エンコード',
mime : 'ターゲット MIME タイプ',
rel : 'ページ→ターゲット関係',
rev : 'ターゲット→ページ関係',
tabindex : 'タッブ指数',
accesskey : 'アクセスキー',
ltr : '左から右へ',
rtl : '右から左へ'
});
