// RO lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Popup',
events_tab : 'Evenimente',
advanced_tab : 'Avanasat',
general_props : 'Propriet&#259;&#355;i generale',
popup_props : 'Proprien&#259;&#355;i popup',
event_props : 'Evenimente',
advanced_props : 'Propriet&#259;&#355;i avansate',
popup_opts : 'Op&#355;iuni',
anchor_names : 'Ancore',
target_same : 'Deschide &#238;n aceea&#351;i fereastr&#259; / frame',
target_parent : 'Deschide &#238;n fereastra / frame-ul p&#259;rinte',
target_top : 'Deschide &#238;n frame-ul de deasupra (&#238;nlocuie&#351;te toate frame-urile)',
target_blank : 'Deschide &#238;n fereastr&#259; nou&#259;',
popup : 'Popup javascript',
popup_url : 'URL popup',
popup_name : 'Nume fereastr&#259;',
popup_return : 'Insereaz&#259; \'return false\'',
popup_scrollbars : 'Arat&#259; barele de derulare',
popup_statusbar : 'Arat&#259; bara de stare',
popup_toolbar : 'Arat&#259; bare unelte',
popup_menubar : 'Arata bara de meniuri',
popup_location : 'Arat&#259; bara de adrese',
popup_resizable : 'F&#259; fereastra redimensionabil&#259;',
popup_dependent : 'Dependent (doar Mozilla/Firefox)',
popup_size : 'Dimensiune',
popup_position : 'Pozi&#355;ie (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'Clase',
target_name : 'Nume &#355;int&#259;',
langdir : 'Direc&#355;ie limb&#259;',
target_langcode : 'Limba &#355;int&#259;',
langcode : 'Cod limb&#259;',
encoding : 'Codare caractere &#355;int&#259;',
mime : 'Tipul MIME &#355;int&#259;',
rel : 'Rela&#355;ia pagin&#259; c&#259;tre &#355;int&#259;',
rev : 'Rela&#355;ia &#355;int&#259; c&#259;tre pagin&#259;',
tabindex : 'Index etichet&#259;',
accesskey : 'Cheie de acces',
ltr : 'St&#226;nga la dreapta',
rtl : 'Dreapta la st&#238;nga'
});
