// RU lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Основные',
popup_tab : 'Всплывающие',
events_tab : 'События',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
popup_props : 'Свойства всплывющих элементов',
event_props : 'События',
advanced_props : 'Расширенные настройки',
popup_opts : 'Опции',
anchor_names : 'Якоря',
target_same : 'Открывать в этом окне / фрейме',
target_parent : 'Открывать в родительском окне / фрейме',
target_top : 'Открывать в верхнем фрейме (заменять все фреймы)',
target_blank : 'Открывать в новом окне',
popup : 'Всплывающее окно Javascript',
popup_url : 'Всплывающий URL',
popup_name : 'Имя окна',
popup_return : 'Вставить \'return false\'',
popup_scrollbars : 'Показывать линейки прокрутки',
popup_statusbar : 'Показывать строку состояния',
popup_toolbar : 'Показывать панели инструментов',
popup_menubar : 'Показывать панель меню',
popup_location : 'Показывать панель расположения',
popup_resizable : 'Позволить изменять размеры окна',
popup_dependent : 'Зависимость (только Mozilla/Firefox)',
popup_size : 'Размер',
popup_position : 'Расположение (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя цели',
langdir : 'Направление письма в языке',
target_langcode : 'Целевой язык',
langcode : 'Код языка',
encoding : 'Целевая кодировка',
mime : 'Целевой MIME тип',
rel : 'Зависимость страница -> цель',
rev : 'Зависимость цель -> страница',
tabindex : 'Индекс таблицы',
accesskey : 'Ключ доступа',
ltr : 'Слева направо',
rtl : 'Справа налево'
});
