/**
 * Slovak lang variables 
 * encoding: utf-8
 * 
 * @author Marián Zvalo marian.zvalo@student.umb.sk
 *    
 * $Id: sk.js,v 1.1 2006/02/28 20:56:44 spocke Exp $ 
 */  

tinyMCE.addToLang('',{
insert_link_target_same : 'Otvoríť v rovnakom okne/ráme',
insert_link_target_parent : 'Otvoríť v rodičovském okne/ráme',
insert_link_target_top : 'Otvoriť v najvyššom ráme (prepíše všetky rámy)',
insert_link_target_blank : 'Otvoríť v novom okne',
insert_link_target_named : 'Otvoríť v okne',
insert_link_popup : 'JS-Popup',
insert_link_popup_url : 'Popup URL',
insert_link_popup_name : 'Názov okna',
insert_link_popup_return : 'Vložiť \'return false\'',
insert_link_popup_scrollbars : 'Ukázať posúvníky',
insert_link_popup_statusbar : 'Ukázať stavový riadok',
insert_link_popup_toolbar : 'Ukázať ovládaciu lištu',
insert_link_popup_menubar : 'Ukázať menu',
insert_link_popup_location : 'Ukázať lištu umiestení',
insert_link_popup_resizable : 'Premenlivá veľkosť okna',
insert_link_popup_size : 'Velikosť',
insert_link_popup_position : 'Umiestnenie (X/Y)',
insert_link_popup_missingtarget : 'Vložte názov cieľa alebo vyberte inú voľbu.',
advlink_general_tab : 'Hlavné',
advlink_popup_tab : 'Nové okno',
advlink_events_tab : 'Udalosti',
advlink_advanced_tab : 'Rozšírené',
advlink_general_props : 'Hlavné nastavenia',
advlink_popup_props : 'Nastavenia nového okna',
advlink_event_props : 'Udalosti prehliadača',
advlink_advanced_props : 'Rozšírené nastavenia',
advlink_popup_opts : 'Voľby',
advlink_anchor_names : 'Ukotvenia',
advlink_target_same : 'Otvoriť v aktuálnom okne / ráme',
advlink_target_parent : 'Otvoriť v materskom okne / ráme',
advlink_target_top : 'Otvoriť v najvyššom ráme (prepíše všetky rámy)',
advlink_target_blank : 'Otvoriť v novom okne',
advlink_popup : 'Nové okno prehliadača',
advlink_popup_url : 'Adresa nového okna',
advlink_popup_name : 'Názov okna',
advlink_popup_return : 'Vložiť \'return false\'',
advlink_popup_scrollbars : 'Zobraziť posuvníky',
advlink_popup_statusbar : 'Zobraziť stavový riadok',
advlink_popup_toolbar : 'Zobraziť nástroje',
advlink_popup_menubar : 'Zobraziť menu',
advlink_popup_location : 'Zobraziť navigačný panel',
advlink_popup_resizable : 'Umožniť zmenu veľkosti',
advlink_popup_dependent : 'Závislosť (iba Mozilla/Firefox)',
advlink_popup_size : 'Veľkosť',
advlink_popup_position : 'Pozícia (X/Y)',
advlink_id : 'Id',
advlink_style: 'CSS štýl',
advlink_classes : 'Trieda',
advlink_target_name : 'Názov elementu',
advlink_langdir : 'Smerovanie textu',
advlink_target_langcode : 'Jazyk cieľa',
advlink_langcode : 'Kód jazyka cieľa',
advlink_encoding : 'Znakové kódovanie cieľa',
advlink_mime : 'MIME typ cieľa',
advlink_rel : 'Vzťah stránky k cieľu',
advlink_rev : 'Vzťah cieľa k stránke',
advlink_tabindex : 'Poradie pre tabulátor',
advlink_accesskey : 'Klávesová skratka',
advlink_ltr : 'Z ľava do prava',
advlink_rtl : 'Z prava do ľava'
});

