// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Te pergjithshme',
popup_tab : 'Popup',
events_tab : 'Eventet',
advanced_tab : 'E Avancuar',
general_props : 'Te dhena te pergjithshme',
popup_props : 'Te dhenat e Popup',
event_props : 'Te dhenat e Eventeve',
advanced_props : 'Te dhena te Avancuara',
popup_opts : 'Mundesi',
anchor_names : 'Spiranca',
target_same : 'Hape ne kete dritare / kornize',
target_parent : ' dritaren / kornizen prind',
target_top : 'Hape ne kornizen e pare(i zevendeson te gjitha kornizat)',
target_blank : 'Hape ne dritare te re',
popup : 'Popup me Javascript ',
popup_url : 'URL e Popup',
popup_name : 'Emrio i Dritares',
popup_return : 'Nderfut kodin \'return false\'',
popup_scrollbars : 'Trego shiritat e kontrollit',
popup_statusbar : 'Trego shiritin e gjendjes',
popup_toolbar : 'Trego shiritat e veglave',
popup_menubar : 'Trego shiritin e Menu-se',
popup_location : 'Trego shiritin e vendodhjes',
popup_resizable : 'Beje dritaren te ndryshueshme',
popup_dependent : 'E varur (vetem Mozilla/Firefox)',
popup_size : 'Madhesi',
popup_position : 'Pozicioni (X/Y)',
id : 'Id',
style: 'Stili',
classes : 'Klasat',
target_name : 'Emri i objektivit',
langdir : 'Drejtimi i Gjuhes',
target_langcode : 'Gjuha e objektivit',
langcode : 'Kodi i gjuhes',
encoding : 'Kodimi i karaktereve te objektivit',
mime : 'Tipi MIME i objektivit',
rel : 'Relacioni i faqes me objektivin',
rev : 'Relacioni i objektivit me faqen',
tabindex : 'Numeri i Tab',
accesskey : 'Çelsei',
ltr : 'Nga e majta ne te djathte',
rtl : 'Nga e djathta ne te majte'
});