// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Generalno',
popup_tab : 'Popup',
events_tab : 'Događaji',
advanced_tab : 'Napredno',
general_props : 'Generalna podešavanja',
popup_props : 'Popup podešavanja',
event_props : 'Događaji',
advanced_props : 'Napredna podešavanja',
popup_opts : 'Opcije',
anchor_names : 'Sidra',
target_same : 'Otvaranje u ovom prozoru / frejmu',
target_parent : 'Otvaranje u roditeljskom prozoru / frejmu',
target_top : 'Otvaranje u frejmu na vrhu (zamenjuje sve frejmove)',
target_blank : 'Otvaranje u novom prozoru',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Ime prozora',
popup_return : 'Ubacivanje \'return false\'',
popup_scrollbars : 'Prikazivanje skrolbarova',
popup_statusbar : 'Prikazivanje status bara',
popup_toolbar : 'Prikazivanje toolbarova',
popup_menubar : 'Prikazivanje menija',
popup_location : 'Prikazivanje lokacije',
popup_resizable : 'Pravljenje prozora promenljive veličine',
popup_dependent : 'Zavisno (samo Mozilla/Firefox)',
popup_size : 'Veličina',
popup_position : 'Pozicija (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'Klase',
target_name : 'Ime mete',
langdir : 'Jezički pravac',
target_langcode : 'Jezik mete',
langcode : 'Jezički kod',
encoding : 'Jezički encoding',
mime : 'MIME tip mete',
rel : 'Relacija strana meta',
rev : 'Relacija meta strana',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Levo ka desno',
rtl : 'Desno ka levo'
});
