// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Generella inställningar',
popup_tab : 'Popup',
events_tab : 'Händelser',
advanced_tab : 'Avancerade inställningar',
general_props : 'Generella inställningar',
popup_props : 'Popup inställningar',
event_props : 'Händelser',
advanced_props : 'Generella inställningar',
popup_opts : 'Inställningar',
anchor_names : 'Bokmärken',
target_same : 'Öppna i samma fönster / ram',
target_parent : 'Öppna i underliggande fönster / ram',
target_top : 'Öppna i toppramen (ersätter alla ramar)',
target_blank : 'Öppna i ett nytt fönster',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Fönster namn',
popup_return : 'Sätt in \'return false\'',
popup_scrollbars : 'Visa scrollningslist',
popup_statusbar : 'Visa statusfält',
popup_toolbar : 'Visa verktygsfält',
popup_menubar : 'Visa menyknappar',
popup_location : 'Visa adressfält',
popup_resizable : 'Gör fönstret skalbart',
popup_dependent : 'Beroende fönster (endast i Mozilla/Firefox)',
popup_size : 'Storlek',
popup_position : 'Position (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'Stilmallsklasser',
target_name : 'Målnamn',
langdir : 'Skriftriktning',
target_langcode : 'Målets språk',
langcode : 'Språkkod',
encoding : 'Teckenkodning',
mime : 'Målets MIME-typ',
rel : 'Relation sida till mål',
rev : 'Relation mål till sida',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Vänster till höger',
rtl : 'Höger till vänster'
});
