// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Основні',
popup_tab : 'Зпливаючі',
events_tab : 'Події',
advanced_tab : 'Розширені',
general_props : 'Основні властивості',
popup_props : 'Властивості зпливючіх елементів',
event_props : 'Події',
advanced_props : 'Розширені настройки',
popup_opts : 'Опції',
anchor_names : 'Якорі',
target_same : 'Відкривати у цьому вікні / фреймі',
target_parent : 'Відкривати у батьківському вікні / фреймі',
target_top : 'Відкривати у верхньому фреймі (заміняти все фрейми)',
target_blank : 'Відкривати з новому вікні',
popup : 'Зпливаче вікно Javascript',
popup_url : 'Зпливаючий URL',
popup_name : 'Ім\'я вікна',
popup_return : 'Вставити \'return false\'',
popup_scrollbars : 'Показувати лінійки прокручування',
popup_statusbar : 'Показувати рядок стану',
popup_toolbar : 'Показувати панелі інструментів',
popup_menubar : 'Показувати панель меню',
popup_location : 'Показувати панель розташування',
popup_resizable : 'Дозволити змінювати розміри вікна',
popup_dependent : 'Залежність (лише Mozilla/Firefox)',
popup_size : 'Розмір',
popup_position : 'Розташування (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Класи',
target_name : 'Ім\'я цілі',
langdir : 'Напрямок письма',
target_langcode : 'Цільова мова',
langcode : 'Код мови',
encoding : 'Цільове кодування',
mime : 'Цільовий MIME тип',
rel : 'Залежність сторінка -> ціль',
rev : 'Залежність ціль -> сторінка',
tabindex : 'Індекс таблиці',
accesskey : 'Ключ доступу',
ltr : 'Зліва направо',
rtl : 'Справа наліво'
});
