// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Основн╕',
popup_tab : 'Зпливаюч╕',
events_tab : 'Под╕╖',
advanced_tab : 'Розширен╕',
general_props : 'Основн╕ властивост╕',
popup_props : 'Властивост╕ зпливюч╕х елемент╕в',
event_props : 'Под╕╖',
advanced_props : 'Розширен╕ настройки',
popup_opts : 'Опц╕╖',
anchor_names : 'Якор╕',
target_same : 'В╕дкривати у цьому в╕кн╕ / фрейм╕',
target_parent : 'В╕дкривати у батьк╕вському в╕кн╕ / фрейм╕',
target_top : 'В╕дкривати у верхньому фрейм╕ (зам╕няти все фрейми)',
target_blank : 'В╕дкривати з новому в╕кн╕',
popup : 'Зпливаче в╕кно Javascript',
popup_url : 'Зпливаючий URL',
popup_name : '╤м\'я в╕кна',
popup_return : 'Вставити \'return false\'',
popup_scrollbars : 'Показувати л╕н╕йки прокручування',
popup_statusbar : 'Показувати рядок стану',
popup_toolbar : 'Показувати панел╕ ╕нструмент╕в',
popup_menubar : 'Показувати панель меню',
popup_location : 'Показувати панель розташування',
popup_resizable : 'Дозволити зм╕нювати розм╕ри в╕кна',
popup_dependent : 'Залежн╕сть (лише Mozilla/Firefox)',
popup_size : 'Розм╕р',
popup_position : 'Розташування (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Класи',
target_name : '╤м\'я ц╕л╕ посилання',
langdir : 'Напрямок письма',
target_langcode : 'Ц╕льова мова',
langcode : 'Код мови',
encoding : 'Ц╕льове кодування',
mime : 'Ц╕льовий MIME тип',
rel : 'Залежн╕сть стор╕нка -> ц╕ль',
rev : 'Залежн╕сть ц╕ль -> стор╕нка',
tabindex : '╤ндекс таблиц╕',
accesskey : 'Ключ доступу',
ltr : 'Зл╕ва направо',
rtl : 'Справа нал╕во'
});
