// Initial translation by Michael Makrigiannakis /

tinyMCE.addToLang('media',{
title : 'Εισαγωγή/Διόρθωση ενσωματωμένου media',
desc : 'Εισαγωγή/Διόρθωση ενσωματωμένου media',
general : 'Γενικά',
advanced : 'Για προχωρημένους',
file : 'Αρχείο',
list : 'Λίστα',
size : 'Διαστάσεις',
preview : 'Προεπισκόπηση',
constrain_proportions : 'Περιορισμός αναλογίας',
type : 'Τύπος',
id : 'Κωδ.',
name : 'Όνομα',
class_name : 'Κλάσση',
vspace : 'Κάθετος χώρος',
hspace : 'Οριζόντιος χώρος',
play : 'εκκίνηση',
loop : 'Ατέρμον',
menu : 'Μenu εμφάνισης',
quality : 'Ποιότητα',
scale : 'Κλίμακα',
align : 'Στοίχιση',
salign : 'S-Στοιχιση',
wmode : 'WMode',
bgcolor : 'Παρασκήνιο',
base : 'Base',
flashvars : 'Flash μεταβλητές',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Κρυφό',
controller : 'Controller',
kioskmode : 'Kiosk mode',
playeveryframe : 'Play κάθε frame',
targetcache : 'Cache στόχου',
correction : 'Χωρίς διόρθωση',
enablejavascript : 'Ενεργοποίηση JavaScript',
starttime : 'Χρόνος έναρξης',
endtime : 'Χρόνος λήξης',
href : 'Href',
qtsrcchokespeed : 'Μείωση ταχύτητας',
target : 'Στόχος',
volume : 'Ένταση',
autostart : 'Αυτόματη εκκίνηση',
enabled : 'Ενεργό',
fullscreen : 'Πλήρης οθόνη',
invokeurls : 'Συμπερίληψη URLs',
mute : 'Σίγαση',
stretchtofit : 'Αλλαγή μεγέθους ώστε να ταιριάζει',
windowlessvideo : 'Windowless video',
balance : 'Ισορροπία',
baseurl : 'Base URL',
captioningid : 'Captioning κωδ.',
currentmarker : 'Τρέχων marker',
currentposition : 'Τρέχουσα θέση',
defaultframe : 'Προεπιλεγμένο frame',
playcount : 'Play count',
rate : 'Ρυθμός',
uimode : 'UI Mode',
flash_options : 'Παράμετροι Flash',
qt_options : 'Παράμετροι Quicktime',
wmp_options : 'Παράμετροι Windows media player',
rmp_options : 'Παράμετροι Real media player',
shockwave_options : 'Παράμετροι Shockwave',
autogotourl : 'Αυτόματο goto URL',
center : 'Κέντρο',
imagestatus : 'Κατάσταση εικόνας',
maintainaspect : 'Συντήρηση',
nojava : 'Όχι java',
prefetch : 'Προφόρτωση',
shuffle : 'Τυχαία',
console : 'Κονσόλα',
numloop : 'Αριθμός loops',
controls : 'Έλεγχοι',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Στυλ παραμόρφωσης',
swstretchhalign : 'Οριζόντια παραμόρφωση',
swstretchvalign : 'Κάθετη παραμόρφωση',
sound : 'Ήχος',
progress : 'Πρόοδος',
qtsrc : 'QT Src',
qt_stream_warn : 'Πηγές  rstp sreaming πρέπει να προστίθενται στο πεδίο QT Src στο tab για προχωρημένους.\nΠρέπει επίσηε να προσθέσετε μια μη-steamed εκδοχή στο πεδίο Src..'
});
