// FR lang variables
// Modified by shadow walker, last updated 2007-03-16, based on the work of Motte

tinyMCE.addToLang('media',{
title : 'Ins&eacute;rer / Editer des medias',
desc : 'Ins&eacute;rer / Editer des medias',
general : 'G&eacute;n&eacute;ral',
advanced : 'Avancement',
file : 'Fichier',
list : 'Liste',
size : 'Taille',
preview : 'Pr&eacute;visualisation',
constrain_proportions : 'Garder les proportions',
type : 'Type',
id : 'Id',
name : 'Nom',
class_name : 'Classe',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Lecture automatique',
loop : 'R&eacute;p&eacute;ter',
menu : 'Menu',
quality : 'Qualit&eacute;',
scale : 'Balance',
align : 'Aligner',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Arri�e plan',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Cache',
controller : 'Controleur',
kioskmode : 'Mode Kioske',
playeveryframe : 'Jouer chaque partie',
targetcache : 'Cible cach&eacute;e',
correction : 'Pas de corrections',
enablejavascript : 'Permettre le JavaScript',
starttime : 'D&eacute;but',
endtime : 'Fin',
href : 'Href',
qtsrcchokespeed : 'Vitesse de d&eacute;roulement',
target : 'Cible',
volume : 'Volume',
autostart : 'D&eacute;marrer automatiquement',
enabled : 'Autoris&eacute;',
fullscreen : 'Plein &eacute;cran',
invokeurls : 'Invoke URLs',
mute : 'Muet',
stretchtofit : 'Redimensionner',
windowlessvideo : 'Vid&eacute;o sans fen�re',
balance : 'Balance',
baseurl : 'URL de base',
captioningid : 'Captioning id',
currentmarker : 'Markeur actuel',
currentposition : 'Position actuelle',
defaultframe : 'Par d&eacute;faut',
playcount : 'Nombre delecture',
rate : 'Taux',
uimode : 'Mode UI',
flash_options : 'Options flash',
qt_options : 'Options quicktime',
wmp_options : 'Options windows media player',
rmp_options : 'Options real media player',
shockwave_options : 'Options shockwave',
autogotourl : 'Auto goto URL',
center : 'Centre',
imagestatus : 'Statut de l\'image',
maintainaspect : 'Maintenir l\'aspect',
nojava : 'Pas de java',
prefetch : 'Pr&eacute;-chargement',
shuffle : 'Al&eacute;atoire',
console : 'Console',
numloop : 'Nombre de boucles',
controls : 'Controles',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Son',
progress : 'Avancement',
qtsrc : 'QT Src',
qt_stream_warn : 'Les flux rtsp doivent �re ajout&eacute;s au champ QT Src dans l\'onglet avanc&eacute;.\nVous devriez ajouter une version sans flux au champ Src..',
align_top : 'Haut',
align_right : 'Droite',
align_bottom : 'Bas',
align_left : 'Gauche',
align_center : 'Centrer',
align_top_left : 'Haut gauche',
align_top_right : 'Haut droit',
align_bottom_left : 'Bas gauche',
align_bottom_right : 'Bas droite'
});
