/**
 * IT lang variables
 * 
 * Author : Luciano Vernaschi <luciano@virgilio.it>
 * Last Updated : Mar. 1st, 2007
 * TinyMCE Version : 2.1.0
 */

tinyMCE.addToLang('media',{
title : 'Inserisci o modifica file multimediali',
desc : 'Inserisci o modifica file multimediali',
general : 'Generale',
advanced : 'Avanzate',
file : 'File',
list : 'Lista',
size : 'Dimensioni',
preview : 'Anteprima',
constrain_proportions : 'Mantieni proporzioni',
type : 'Tipo',
id : 'Id',
name : 'Nome',
class_name : 'Classe',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Riproduzione automatica',
loop : 'Cicla',
menu : 'Mostra menu',
quality : 'Qualit&agrave;',
scale : 'Scala',
align : 'Allineamento',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Colore di sfondo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Nascosto',
controller : 'Controller',
kioskmode : 'Kiosk mode',
playeveryframe : 'Mostra tutti i frame',
targetcache : 'Target cache',
correction : 'Nessuna correzione',
enablejavascript : 'Abilita JavaScript',
starttime : 'Tempo iniziale',
endtime : 'Tempo finale',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Target',
volume : 'Volume',
autostart : 'Avvio automatico',
enabled : 'Abilitato',
fullscreen : 'Schermo intero',
invokeurls : 'Invoca URL',
mute : 'Muto',
stretchtofit : 'Riempi',
windowlessvideo : 'Video windowless',
balance : 'Bilanciamento',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Marker corrente',
currentposition : 'Posizione corrente',
defaultframe : 'Frame di default',
playcount : 'Play count',
rate : 'Rate',
uimode : 'Modo UI',
flash_options : 'Opzioni Flash',
qt_options : 'Opzioni Quicktime',
wmp_options : 'Opzioni Windows Media Player',
rmp_options : 'Opzioni Real Media Player',
shockwave_options : 'Opzioni Shockwave',
autogotourl : 'Auto goto URL',
center : 'Centra',
imagestatus : 'Image status',
maintainaspect : 'Maintieni aspetto',
nojava : 'No Java',
prefetch : 'Prefetch',
shuffle : 'Casuale',
console : 'Console',
numloop : 'Num. ripetizioni',
controls : 'Controlli',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Suono',
progress : 'Progresso',
qtsrc : 'QT Src',
qt_stream_warn : 'Le risorse &quot;Streamed RTSP&quot; devono essere aggiunte al campo &quot;QT Src&quot; nelle funzioni avanzate.\n&Egrave; meglio aggiungere anche una versione non in streaming nel campo Src.'
align_top : 'In Alto',
align_right : 'A destra',
align_bottom : 'In basso',
align_left : 'A sinistra',
align_center : 'Al centro',
align_top_left : 'In alto a sinistra',
align_top_right : 'In alto a destra',
align_bottom_left : 'In basso a sinistra',
align_bottom_right : 'In basso a destra'
});
