// NL lang variables
// Door Coen Warmer

tinyMCE.addToLang('media',{
title : 'Invoegen / bewerken video',
desc : 'Invoegen / bewerken video',
general : 'Algemeen',
advanced : 'Geavanceerd',
file : 'Bestand',
list : 'Lijst',
size : 'Verhoudingen',
preview : 'Voorbeeld',
constrain_proportions : 'Leg hoogte-breedte verhoudingen vast',
type : 'Type',
id : 'Id',
name : 'Naam',
class_name : 'Class',
vspace : 'Verticale ruimte',
hspace : 'Horizontale ruimte',
play : 'Automatisch Afspelen',
loop : 'Herhalen',
menu : 'Menu weergeven',
quality : 'Kwaliteit',
scale : 'Schaal',
align : 'Uitlijnen',
salign : 'Uitlijnen',
wmode : 'WMode',
bgcolor : 'Achtergrond kleur',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Verborgen',
controller : 'Controller',
kioskmode : 'Kiosk modus',
playeveryframe : 'Speel elk frame',
targetcache : 'Target cache',
correction : 'Geen correctie',
enablejavascript : 'JavaScript inschakelen',
starttime : 'Starttijd',
endtime : 'Eindtijd',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Doel',
volume : 'Volume',
autostart : 'Automatisch starten',
enabled : 'Ingeschakeld',
fullscreen : 'Volledig scherm',
invokeurls : 'Invoke URLs',
mute : 'Stil',
stretchtofit : 'Uitrekken tot maximale grootte',
windowlessvideo : 'Video zonder venster',
balance : 'Balance',
baseurl : 'Basis URL',
captioningid : 'Captioning id',
currentmarker : 'Huidige marker',
currentposition : 'Huidige positie',
defaultframe : 'Standaard frame',
playcount : 'Afspeel teller',
rate : 'Rate',
uimode : 'UI Modus',
flash_options : 'Flash options',
qt_options : 'Quicktime opties',
wmp_options : 'Windows media player opties',
rmp_options : 'Real media player opties',
shockwave_options : 'Shockwave opties',
autogotourl : 'Automatisch naar Goto-URL gaan',
center : 'Centreren',
imagestatus : 'Beeld status',
maintainaspect : 'Behoud verhoudingen',
nojava : 'Geen Java',
prefetch : 'Prefetch',
shuffle : 'Shuffle',
console : 'Console',
numloop : 'Hoeveel loops',
controls : 'Controls',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch stijl',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Geluid',
progress : 'Voortgang',
qtsrc : 'Quicktime Bron',
qt_stream_warn : 'Gestreamde RTSP bronnen moeten toegevoegd worden aan het Quicktime Bron veld onder het tabblad Geavanceerd.\nHet wordt aangeraden ook een niet streamende versie toe te voegen aan het Bron veld.'
});