/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('media',{
title : 'Inserir/editar mídia incorporada',
desc : 'Inserir/editar mídia incorporada',
general : 'Geral',
advanced : 'Avançado',
file : 'Arquivo',
list : 'Lista',
size : 'Dimensões',
preview : 'Preview',
constrain_proportions : 'Confinar proporções',
type : 'Tipo',
id : 'ID',
name : 'Nome',
class_name : 'Classe',
vspace : 'Espaço-V',
hspace : 'Espaço-H',
play : 'Tocar automaticamente',
loop : 'Loop',
menu : 'Mostrar menu',
quality : 'Qualidade',
scale : 'Escala',
align : 'Alinhamento',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Fundo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Escondido',
controller : 'Controlador',
kioskmode : 'Modo Kiosk',
playeveryframe : 'Tocar cada frame',
targetcache : 'Destino do cache',
correction : 'Sem correção',
enablejavascript : 'Ativar JavaScript',
starttime : 'Tempo de início',
endtime : 'Tempo de fim',
href : 'Href',
qtsrcchokespeed : 'Velocidade do bloqueador',
target : 'Destino',
volume : 'Volume',
autostart : 'Início automático',
enabled : 'Ativado',
fullscreen : 'Tela Cheia',
invokeurls : 'Chamar URLs',
mute : 'Silencioso',
stretchtofit : 'Esticar para caber',
windowlessvideo : 'Vídeo em janela',
balance : 'Balanço',
baseurl : 'URL Base',
captioningid : 'ID de identificação',
currentmarker : 'Marcador atual',
currentposition : 'Posição atual',
defaultframe : 'Frame padrão',
playcount : 'Contador',
rate : 'Taxa',
uimode : 'Modo UI',
flash_options : 'Opções do Flash',
qt_options : 'Opções do Quicktime',
wmp_options : 'Opções do Windows media player',
rmp_options : 'Opções do Real media player',
shockwave_options : 'Opções do Shockwave',
autogotourl : 'Ir automaticamente para URL',
center : 'Centro',
imagestatus : 'Status da imagem',
maintainaspect : 'Manter aspecto',
nojava : 'Sem java',
prefetch : 'Leitura inicial',
shuffle : 'Aleatório',
console : 'Console',
numloop : 'Número de loops',
controls : 'Controles',
scriptcallbacks : 'Script de retorno',
swstretchstyle : 'Estilo para o Stretch',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'Som',
progress : 'Progresso',
qtsrc : 'QT Src',
qt_stream_warn : 'Os recursos do Streamed rtsp podem ser adicionado ao campo QT Src na aba avançada.\nVocê pode também adicionar uma versão não streamer ao comapo Src.',
align_top : 'Acima',
align_right : 'Direita',
align_bottom : 'Abaixo',
align_left : 'Esquerda',
align_center : 'Centro',
align_top_left : 'Acima esquerda',
align_top_right : 'Acima direita',
align_bottom_left : 'Abaixo esquerda',
align_bottom_right : 'Abaixo direita'
});
