// RU lang variables

tinyMCE.addToLang('media',{
title : 'Вставить / редактировать медиа',
desc : 'Вставить / редактировать медиа',
general : 'Основной',
advanced : 'Дополнительный',
file : 'Файл',
list : 'Список',
size : 'Размеры',
preview : 'Предпросмотр',
constrain_proportions : 'Поддерживать пропорции',
type : 'Тип',
id : 'Id',
name : 'Имя',
class_name : 'Класс',
vspace : 'V-Отступ',
hspace : 'H-Отступ',
play : 'Авто проигрывание',
loop : 'Цикл',
menu : 'Показать меню',
quality : 'Качество',
scale : 'Масштаб',
align : 'Выравнивание',
salign : 'S-Выравнивание',
wmode : 'W-Режим',
bgcolor : 'Фон',
base : 'База',
flashvars : 'Переменные флеш',
liveconnect : 'SWLiveConnect',
autohref : 'Авто Ссылка',
cache : 'Кеш',
hidden : 'Скрытый',
controller : 'Контроллер',
kioskmode : 'Режим Kiosk',
playeveryframe : 'Проигрывать каждый кадр',
targetcache : 'Целевой кеш',
correction : 'No correction',
enablejavascript : 'Включить JavaScript',
starttime : 'Время начала',
endtime : 'Время окончания',
href : 'Ссылка',
qtsrcchokespeed : 'Уменьшить скорость',
target : 'Цель',
volume : 'Громкость',
autostart : 'Авто запуск',
enabled : 'Включено',
fullscreen : 'Полный экран',
invokeurls : 'Активизировать ссылки',
mute : 'Тишина',
stretchtofit : 'Растянуть до вхождения',
windowlessvideo : 'Безоконное видео',
balance : 'Баланс',
baseurl : 'Базовая ссылка',
captioningid : 'Id ввода субтитров',
currentmarker : 'Текущая отметка',
currentposition : 'Текущая позиция',
defaultframe : 'Кадр по умолчанию',
playcount : 'Счетчик',
rate : 'Частота',
uimode : 'UI режим',
flash_options : 'Опции Флеш',
qt_options : 'Опции Quicktime',
wmp_options : 'Опции проигрывателя Windows media',
rmp_options : 'Опции проигрывателя Real media',
shockwave_options : 'Опции Shockwave',
autogotourl : 'Авто переход по ссылке',
center : 'Центр',
imagestatus : 'Статус изображения',
maintainaspect : 'Поддерживать аспект',
nojava : 'Без java',
prefetch : 'Упреждение',
shuffle : 'Перемешать',
console : 'Консоль',
numloop : 'Количество циклов',
controls : 'Управления',
scriptcallbacks : 'Обратный вызов скрипта',
swstretchstyle : 'Стиль растяжения',
swstretchhalign : 'H-Выравнивание растяжения',
swstretchvalign : 'V-Выравнивание растяжения',
sound : 'Звук',
progress : 'Прогресс',
qtsrc : 'QT Исх',
qt_stream_warn : 'Потоковые rtsp ресурсы должны быть добавлены в поле QT Исх в дополнительную графу.\nВы также должны добавить не потоковую версию в поле Исх..',
align_top : 'Вверх',
align_right : 'Вправо',
align_bottom : 'Вниз',
align_left : 'Влево',
align_center : 'В центр',
align_top_left : 'Влево - вверх',
align_top_right : 'Вправо - вверх',
align_bottom_left : 'Влево - вниз',
align_bottom_right : 'Вправо - вниз'
});
