// UK lang variables

tinyMCE.addToLang('media',{
title : 'Вставити / редагувати медіа',
desc : 'Вставити / редагувати медіа',
general : 'Основний',
advanced : 'Додатковий',
file : 'Файл',
list : 'Список',
size : 'Розміри',
preview : 'Попередній перегляд',
constrain_proportions : 'Підтримувати пропорції',
type : 'Тип',
id : 'Id',
name : 'Ім\'я',
class_name : 'Клас',
vspace : 'V-Отступ',
hspace : 'H-Отступ',
play : 'Авто програвання',
loop : 'Цикл',
menu : 'Показати меню',
quality : 'Якість',
scale : 'Масштаб',
align : 'Вирівнювання',
salign : 'S-Вирівнювання',
wmode : 'W-Режим',
bgcolor : 'Фон',
base : 'База',
flashvars : 'Перемінні флеш',
liveconnect : 'SWLiveConnect',
autohref : 'Авто Посилання',
cache : 'Кеш',
hidden : 'Прихований',
controller : 'Контролер',
kioskmode : 'Режим Kiosk',
playeveryframe : 'Програвати кожен кадр',
targetcache : 'Цільовий кеш',
correction : 'No correction',
enablejavascript : 'Включити JavaScript',
starttime : 'Час початку',
endtime : 'Час закінчення',
href : 'Посилання',
qtsrcchokespeed : 'Зменшити швидкість',
target : 'Ціль',
volume : 'Гучність',
autostart : 'Авто запуск',
enabled : 'Включено',
fullscreen : 'Повний екран',
invokeurls : 'Активізувати посилання',
mute : 'Тиша',
stretchtofit : 'Розтягнути до входження',
windowlessvideo : 'Безвіконне відео',
balance : 'Баланс',
baseurl : 'Базове посилання',
captioningid : 'Id введення субтитрів',
currentmarker : 'Поточна позначка',
currentposition : 'Поточна позиція',
defaultframe : 'Кадр за умовчанням',
playcount : 'Лічильник',
rate : 'Частота',
uimode : 'UI режим',
flash_options : 'Опції Флеш',
qt_options : 'Опції Quicktime',
wmp_options : 'Опції програвача Windows media',
rmp_options : 'Опції програвача Real media',
shockwave_options : 'Опції Shockwave',
autogotourl : 'Авто перехід за посиланням',
center : 'Центр',
imagestatus : 'Статус зображення',
maintainaspect : 'Підтримувати аспект',
nojava : 'Без java',
prefetch : 'Випередження',
shuffle : 'Перемішати',
console : 'Консоль',
numloop : 'Кількість циклів',
controls : 'Управління',
scriptcallbacks : 'Зворотний виклик скрипта',
swstretchstyle : 'Стиль розтягування',
swstretchhalign : 'H-Вирівнювання розтягування',
swstretchvalign : 'V-Вирівнювання розтягування',
sound : 'Звук',
progress : 'Прогрес',
qtsrc : 'QT Джерело',
qt_stream_warn : 'Потокові rtsp ресурси мають бути додані до поля QT Джерело в додаткову закладку.\nВам також слід додати непотокову версію до поля Джерело.',
align_top : 'Вгору',
align_right : 'Вправо',
align_bottom : 'Вниз',
align_left : 'Вліво',
align_center : 'До центру',
align_top_left : 'Вліво - вгору',
align_top_right : 'Вправо - вгору',
align_bottom_left : 'Вліво - вниз',
align_bottom_right : 'Вправо - вниз'
});
