// UK lang variables

tinyMCE.addToLang('media',{
title : 'Вставити / редагувати мед╕а',
desc : 'Вставити / редагувати мед╕а',
general : 'Основний',
advanced : 'Додатковий',
file : 'Файл',
list : 'Список',
size : 'Розм╕ри',
preview : 'Попередн╕й перегляд',
constrain_proportions : 'П╕дтримувати пропорц╕╖',
type : 'Тип',
id : 'Id',
name : '╤м\'я',
class_name : 'Клас',
vspace : 'V-Отступ',
hspace : 'H-Отступ',
play : 'Авто програвання',
loop : 'Цикл',
menu : 'Показати меню',
quality : 'Як╕сть',
scale : 'Масштаб',
align : 'Вир╕внювання',
salign : 'S-Вир╕внювання',
wmode : 'W-Режим',
bgcolor : 'Фон',
base : 'База',
flashvars : 'Перем╕нн╕ флеш',
liveconnect : 'SWLiveConnect',
autohref : 'Авто Посилання',
cache : 'Кеш',
hidden : 'Прихований',
controller : 'Контролер',
kioskmode : 'Режим Kiosk',
playeveryframe : 'Програвати кожен кадр',
targetcache : 'Ц╕льовий кеш',
correction : 'No correction',
enablejavascript : 'Включити JavaScript',
starttime : 'Час початку',
endtime : 'Час зак╕нчення',
href : 'Посилання',
qtsrcchokespeed : 'Зменшити швидк╕сть',
target : 'Ц╕ль',
volume : 'Гучн╕сть',
autostart : 'Авто запуск',
enabled : 'Включено',
fullscreen : 'Повний екран',
invokeurls : 'Актив╕зувати посилання',
mute : 'Тиша',
stretchtofit : 'Розтягнути до входження',
windowlessvideo : 'Безв╕конне в╕део',
balance : 'Баланс',
baseurl : 'Базове посилання',
captioningid : 'Id введення субтитр╕в',
currentmarker : 'Поточна позначка',
currentposition : 'Поточна позиц╕я',
defaultframe : 'Кадр за умовчанням',
playcount : 'Л╕чильник',
rate : 'Частота',
uimode : 'UI режим',
flash_options : 'Опц╕╖ Флеш',
qt_options : 'Опц╕╖ Quicktime',
wmp_options : 'Опц╕╖ програвача Windows media',
rmp_options : 'Опц╕╖ програвача Real media',
shockwave_options : 'Опц╕╖ Shockwave',
autogotourl : 'Авто перех╕д за посиланням',
center : 'Центр',
imagestatus : 'Статус зображення',
maintainaspect : 'П╕дтримувати аспект',
nojava : 'Без java',
prefetch : 'Випередження',
shuffle : 'Перем╕шати',
console : 'Консоль',
numloop : 'К╕льк╕сть цикл╕в',
controls : 'Управл╕ння',
scriptcallbacks : 'Зворотний виклик скрипта',
swstretchstyle : 'Стиль розтягування',
swstretchhalign : 'H-Вир╕внювання розтягування',
swstretchvalign : 'V-Вир╕внювання розтягування',
sound : 'Звук',
progress : 'Прогрес',
qtsrc : 'QT Джерело',
qt_stream_warn : 'Потоков╕ rtsp ресурси мають бути додан╕ до поля QT Джерело в додаткову закладку.\nВам також сл╕д додати непотокову верс╕ю до поля Джерело.',
align_top : 'Вгору',
align_right : 'Вправо',
align_bottom : 'Вниз',
align_left : 'Вл╕во',
align_center : 'До центру',
align_top_left : 'Вл╕во - вгору',
align_top_right : 'Вправо - вгору',
align_bottom_left : 'Вл╕во - вниз',
align_bottom_right : 'Вправо - вниз'
});
