/**
 * ES lang variables
 * 
 * Authors : Eneko Castresana Vara
 * Last Updated : July 14, 2006
 * TinyMCE Version : 2.0.6.1
 */
 
tinyMCE.addToLang('fullpage',{
	title : 'Propiedades del documento',
	desc : 'Propiedades del documento',
	meta_tab : 'General',
	appearance_tab : 'Apariencia',
	advanced_tab : 'Avanzado',
	meta_props : 'Informaci&oacute;n Meta',
	langprops : 'Idioma y codificaci&oacute;n',
	meta_title : 'T&iacute;tulo',
	meta_keywords : 'Palabras clave',
	meta_description : 'Descripci&oacute;n',
	meta_robots : 'Robots',
	doctypes : 'Tipo de documento',
	langcode : 'C&oacute;digo del idioma',
	langdir : 'Direcci&oacute;n del idioma',
	ltr : 'Izquierda a derecha',
	rtl : 'Derecha a izquierda',
	xml_pi : 'Declaraci&oacute;n XML',
	encoding : 'Codificaci&oacute;n de caracteres',
	appearance_bgprops : 'Propiedades de fondo',
	appearance_marginprops : 'M&aacute;rgenes del cuerpo',
	appearance_linkprops : 'Color de los enlaces',
	appearance_textprops : 'Propiedades del texto',
	bgcolor : 'Color de fondo',
	bgimage : 'Imagen de fondo',
	left_margin : 'Margen izquierdo',
	right_margin : 'Margen derecho',
	top_margin : 'Margen superior',
	bottom_margin : 'Margen inferior',
	text_color : 'Color del texto',
	font_size : 'Tama&ntilde;o de la fuente',
	font_face : 'Familia de la fuente',
	link_color : 'Color de los enlaces',
	hover_color : 'Color de resalte',
	visited_color : 'Color de visitado',
	active_color : 'Color de activo',
	textcolor : 'Color',
	fontsize : 'Tama&ntilde;o de la fuente',
	fontface : 'Familia de la fuente',
	meta_index_follow : 'Indexar y seguir enlaces',
	meta_index_nofollow : 'Indexar y no seguir enlaces',
	meta_noindex_follow : 'No indexar pero seguir enlaces',
	meta_noindex_nofollow : 'No indexar ni seguir enlaces',
	appearance_style : 'Hoja de estilos y propiedades de estilo',
	stylesheet : 'Hoja de estilos',
	style : 'Estilo',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'A&ntilde;adir nuevo elemento',
	remove : 'Quitar elemento seleccionado',
	moveup : 'Mover el elemento seleccionado hacia arriba',
	movedown : 'Mover el elemento seleccionado hacia abajo',
	head_elements : 'Elementos de cabecera',
	info : 'Informaci&oacute;n',
	info_text : '',
	add_title : 'Elemento de t&iacute;tulo',
	add_meta : 'Elemento Meta',
	add_script : 'Elemento de script',
	add_style : 'Elemento de estilo',
	add_link : 'Elemento de enlace',
	add_base : 'Elemento base',
	add_comment : 'Nodo comentario',
	title_element : 'Elemento de t&iacute;tulo',
	script_element : 'Elemento de script',
	style_element : 'Elemento de estilo',
	base_element : 'Elemento base',
	link_element : 'Elemento de enlace',
	meta_element : 'Elemento Meta',
	comment_element : 'Comentario',
	src : 'Fuente',
	language : 'Idioma',
	href : 'Referencia',
	target : 'Destino',
	rel : 'Rel',
	type : 'Tipo',
	charset : 'C&oacute;digo de caracteres',
	defer : 'Defer',
	media : 'Media',
	properties : 'Propiedades',
	name : 'Nombre',
	value : 'Valor',
	content : 'Contenido',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Idioma de referencia',
	general_props : 'General',
	advanced_props : 'Avanzado',
	delta_width : 0,
	delta_height : 0
});
