/**
 * IT lang variables
 * 
 * Author : Luciano Vernaschi <luciano@virgilio.it>
 * Last Updated : Mar. 1st, 2007
 * TinyMCE Version : 2.1.0
 */

tinyMCE.addToLang('fullpage',{
	title : 'Propriet&agrave; del documento',
	desc : 'Propriet&agrave; del documento',
	meta_tab : 'Generale',
	appearance_tab : 'Aspetto',
	advanced_tab : 'Avanzate',
	meta_props : 'Tag Meta',
	langprops : 'Lingua e codifica',
	meta_title : 'Titolo',
	meta_keywords : 'Parole chiave',
	meta_description : 'Descrizione',
	meta_robots : 'Robots',
	doctypes : 'Doctype',
	langcode : 'Codifica lingua',
	langdir : 'Direzione del testo',
	ltr : 'Da sinistra a destra',
	rtl : 'Da destra a sinistra',
	xml_pi : 'Dichiarazione XML',
	encoding : 'Codifica caratteri',
	appearance_bgprops : 'Propriet&agrave; dello sfondo',
	appearance_marginprops : 'Margine',
	appearance_linkprops : 'Colori dei link',
	appearance_textprops : 'Propriet&agrave; del testo',
	bgcolor : 'Colore di sfondo',
	bgimage : 'Immagine di sfondo',
	left_margin : 'Margine sinistro',
	right_margin : 'Margine destro',
	top_margin : 'Margine superiore',
	bottom_margin : 'Margine inferiore',
	text_color : 'Colore del testo',
	font_size : 'Dimensione del carattere',
	font_face : 'Font',
	link_color : 'Colore dei link',
	hover_color : 'Colore del link sotto il mouse',
	visited_color : 'Colore dei link visitati',
	active_color : 'Colore del link attivo',
	textcolor : 'Colore',
	fontsize : 'Dimensione del carattere',
	fontface : 'Font',
	meta_index_follow : 'Indicizza e segui i link',
	meta_index_nofollow : 'Indicizza, ma non seguire i link',
	meta_noindex_follow : 'Non indicizzare, ma segui i link',
	meta_noindex_nofollow : 'Non indicizzare e non seguire i link',
	appearance_style : 'Fogli di stile e propriet&agrave; degli stili',
	stylesheet : 'Foglio di stile',
	style : 'Stile',
	author : 'Autore',
	copyright : 'Copyright',
	add : 'Aggiungi nuovo elemento',
	remove : 'Rimuovi elemento selezionato',
	moveup : 'Muovi elemento selezionato verso l\'alto',
	movedown : 'Muovi elemento selezionato verso il basso',
	head_elements : 'Elementi Head',
	info : 'Informazioni',
	info_text : '',
	add_title : 'Elemento Title',
	add_meta : 'Elemento Meta',
	add_script : 'Elemento Script',
	add_style : 'Elemento Style',
	add_link : 'ELemento Link',
	add_base : 'Elemento Base',
	add_comment : 'Nodo Commento',
	title_element : 'Elemento Title',
	script_element : 'Elemento Script',
	style_element : 'Elemento Style',
	base_element : 'Elemento Base',
	link_element : 'ELemento Link',
	meta_element : 'Elemento Met',
	comment_element : 'Commento',
	src : 'Src',
	language : 'Language',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Type',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Properties',
	name : 'Name',
	value : 'Value',
	content : 'Content',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Generale',
	advanced_props : 'Avanzate',
	delta_width : 0,
	delta_height : 0
});
