/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('fullpage',{
	title : 'Propriedades do documento',
	desc : 'Propriedades do documento',
	meta_tab : 'Geral',
	appearance_tab : 'Aparência',
	advanced_tab : 'Avançado',
	meta_props : 'Informação Meta',
	langprops : 'Codificação e idioma',
	meta_title : 'Título',
	meta_keywords : 'Palavras',
	meta_description : 'Descrição',
	meta_robots : 'Robos',
	doctypes : 'Tipo de documento',
	langcode : 'Código do idioma',
	langdir : 'Direção do idioma',
	ltr : 'Esquerda para direita',
	rtl : 'Direita para esquerda',
	xml_pi : 'Declaração XML',
	encoding : 'Codificação de caracteres',
	appearance_bgprops : 'Propriedades do fundo',
	appearance_marginprops : 'Margens do corpo',
	appearance_linkprops : 'Cores dos links',
	appearance_textprops : 'Propriedades do texto',
	bgcolor : 'Cor do fundo',
	bgimage : 'Fundo da imagem',
	left_margin : 'Margem esquerda',
	right_margin : 'Margem direita',
	top_margin : 'Margem superior',
	bottom_margin : 'Margem inferior',
	text_color : 'Cor do texto',
	font_size : 'Tamanho da fonte',
	font_face : 'Tipo de fonte',
	link_color : 'Cor do link',
	hover_color : 'Cor do mouse sobre',
	visited_color : 'Cor do link visitado',
	active_color : 'Cor do link ativo',
	textcolor : 'Cor',
	fontsize : 'Tamanho da fonte',
	fontface : 'Tipo de fonte',
	meta_index_follow : 'Indexar e seguir os links',
	meta_index_nofollow : 'Indexar e não seguir os links',
	meta_noindex_follow : 'Não indexar, mas seguir os links',
	meta_noindex_nofollow : 'Não indexar e não seguir os links',
	appearance_style : 'Folha de estilo e propriedades dos estilos',
	stylesheet : 'Folha de estilo',
	style : 'Estilo',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'Adicionar novo elemento',
	remove : 'Remover elemento selecionado',
	moveup : 'Mover selecionado para cima',
	movedown : 'Mover selecionado para baixo',
	head_elements : 'Elementos do cabeçalho',
	info : 'Informação',
	info_text : '',
	add_title : 'Elemento Título',
	add_meta : 'Elemento Meta',
	add_script : 'Elemento Script',
	add_style : 'Elemento Estilo',
	add_link : 'Elemento Link',
	add_base : 'Elemento Base',
	add_comment : 'Comentário',
	title_element : 'Título',
	script_element : 'Script',
	style_element : 'Estilo',
	base_element : 'Base',
	link_element : 'Link',
	meta_element : 'Meta',
	comment_element : 'Comentário',
	src : 'Src',
	language : 'Idioma',
	href : 'Href',
	target : 'Destino',
	rel : 'Rel',
	type : 'Tipo',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Midia',
	properties : 'Propriedades',
	name : 'Nome',
	value : 'Valor',
	content : 'Conteúdo',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Geral',
	advanced_props : 'Avançado',
	delta_width : 0,
	delta_height : 0
});
