// RO lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Propriet&#259;&#355;i document',
	desc : 'Propriet&#355;i document',
	meta_tab : 'General',
	appearance_tab : 'Aspect',
	advanced_tab : 'Avansat',
	meta_props : 'Meta informa&#355;ii',
	langprops : 'Limb&#259; &#351;i codificare',
	meta_title : 'Titlu',
	meta_keywords : 'Cuvinte cheie',
	meta_description : 'Descriere',
	meta_robots : 'Robo&#355;i',
	doctypes : 'Doctype',
	langcode : 'Cod limb&#259;',
	langdir : 'Direc&#355;ie limb&#259;',
	ltr : 'St&#226;nga la dreapta',
	rtl : 'Dreapta la st&#226;nga',
	xml_pi : 'declara&#355;ie XML',
	encoding : 'Codificare caractere',
	appearance_bgprops : 'Propriet&#259;&#355;i fundal',
	appearance_marginprops : 'Marginile corpului',
	appearance_linkprops : 'Culori leg&#259;turi',
	appearance_textprops : 'Propriet&#259;&#355;i text',
	bgcolor : 'Culoare fundal',
	bgimage : 'Imagine de fundal',
	left_margin : 'Marginea st&#226;ng&#259;',
	right_margin : 'Marginea dreapt&#259;',
	top_margin : 'Marginea de sus',
	bottom_margin : 'Marginea bazei',
	text_color : 'Culoare text',
	font_size : 'Dimensiune font',
	font_face : 'Stil font',
	link_color : 'Culoare leg&#259;tur&#259;',
	hover_color : 'Culoare la trecere peste',
	visited_color : 'Culoare vizitat',
	active_color : 'Culoare activ',
	textcolor : 'Culoare',
	fontsize : 'Dimensiune font',
	fontface : 'Familie font',
	meta_index_follow : 'Indexeaz&#259; &#351;i urmeaz&#259; leg&#259;turile',
	meta_index_nofollow : 'Indexeaz&#259; &#351;i nu urma leg&#259;turile',
	meta_noindex_follow : 'Nu indexa dar urmeaz&#259; leg&#259;turile',
	meta_noindex_nofollow : 'Nu indexa &#351;i nu urma leg&#259;turile',
	appearance_style : 'Propriet&#259;&#355;i  stil &#351;i foaie de stiluri',
	stylesheet : 'Foaie de stiluri',
	style : 'Stil',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'Adaug&#259; element nou',
	remove : '&#351;terge elementul selectat',
	moveup : 'Mut&#259; elementul selectat sus',
	movedown : 'Mut&#259; elementul selectat jos',
	head_elements : 'Elemente head',
	info : 'Informa&#355;ii',
	info_text : '',
	add_title : 'Elementul title',
	add_meta : 'Elementul meta',
	add_script : 'Elementul script',
	add_style : 'Elementul style',
	add_link : 'Elementul link',
	add_base : 'Elementul base',
	add_comment : 'Nod comentarii',
	title_element : 'Elementul title',
	script_element : 'Elementul script',
	style_element : 'Elementul style',
	base_element : 'Elementul base',
	link_element : 'Elementul link',
	meta_element : 'Elementul meta',
	comment_element : 'Comentariu',
	src : 'Surs&#259;',
	language : 'Language',
	href : 'Href',
	target : '&#355;int&#259;',
	rel : 'Rel',
	type : 'Tip',
	charset : 'Set de caractere',
	defer : '&#206;nm&#226;nare',
	media : 'Mediu',
	properties : 'Propriet&#259;&#355;i',
	name : 'Nume',
	value : 'Valoare',
	content : 'Con&#355;inut',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Limb&#259; Href',
	general_props : 'General',
	advanced_props : 'Avansat',
	delta_width : 0,
	delta_height : 0
});
