// RU lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Свойства документа',
	desc : 'Свойства документа',
	meta_tab : 'Основные',
	appearance_tab : 'Видимость',
	advanced_tab : 'Дополнительные',
	meta_props : 'Мета информация',
	langprops : 'Язык и кодировка',
	meta_title : 'Название',
	meta_keywords : 'Ключевые слова',
	meta_description : 'Описание',
	meta_robots : 'Роботы',
	doctypes : 'Тип документа (Doctype)',
	langcode : 'Код языка',
	langdir : 'Направление языка',
	ltr : 'Слева направо',
	rtl : 'Справа налево',
	xml_pi : 'XML декларация',
	encoding : 'Кодировка',
	appearance_bgprops : 'Свойства фона',
	appearance_marginprops : 'Отступы',
	appearance_linkprops : 'Цвет ссылок',
	appearance_textprops : 'Свойства текста',
	bgcolor : 'Цвет фона',
	bgimage : 'Фоновое изображение',
	left_margin : 'Отступ слева',
	right_margin : 'Отступ справа',
	top_margin : 'Отступ сверху',
	bottom_margin : 'Отступ снизу',
	text_color : 'Цвет текста',
	font_size : 'Размер шрифта',
	font_face : 'Шрифт',
	link_color : 'Цвет ссылки',
	hover_color : 'Цвет при наведении на ссылку',
	visited_color : 'Цвет посещенной ссылки',
	active_color : 'Цвет активной ссылки',
	textcolor : 'Цвет',
	fontsize : 'Размер шрифта',
	fontface : 'Тип шрифта',
	meta_index_follow : 'Индексировать и следовать по ссылкам',
	meta_index_nofollow : 'Индексировать и не следовать по ссылкам',
	meta_noindex_follow : 'Не индексировать, но следовать по ссылкам',
	meta_noindex_nofollow : 'Не индексировать и не следовать по ссылкам',
	appearance_style : 'Таблица стилей и свойства стиля',
	stylesheet : 'Таблица стилей',
	style : 'Стиль',
	author : 'Автор',
	copyright : 'Авторское право',
	add : 'Добавить новый элемент',
	remove : 'Удалить выделенный элемент',
	moveup : 'Переместить выбранный элемент вверх',
	movedown : 'Переместить выделенный элемент вниз',
	head_elements : 'Элемент главный',
	info : 'Информация',
	info_text : '',
	add_title : 'Элемент название',
	add_meta : 'Элемент мета',
	add_script : 'Элемент скрипт',
	add_style : 'Элемент стиль',
	add_link : 'Элемент ссылка',
	add_base : 'Элемент базовый',
	add_comment : 'Элемент комментарий',
	title_element : 'Элемент название',
	script_element : 'Элемент скрипт',
	style_element : 'Элемент стиль',
	base_element : 'Элемент базовый',
	link_element : 'Элемент ссылка',
	meta_element : 'Элемент мета',
	comment_element : 'Комментарий',
	src : 'Источник',
	language : 'Язык',
	href : 'Href',
	target : 'Цель',
	rel : 'Вып',
	type : 'Тип',
	charset : 'Кодировка',
	defer : 'Задержка',
	media : 'Медиа',
	properties : 'Свойства',
	name : 'Имя',
	value : 'Значение',
	content : 'Контент',
	rel : 'Вып',
	rev : 'Обр',
	hreflang : 'Href язык',
	general_props : 'Основные',
	advanced_props : 'Дополнительные',
	delta_width : 0,
	delta_height : 0
});
