// UK lang variables

tinyMCE.addToLang('fullpage',{
        title : 'Te dhenat  dokumentit',
        desc : 'Te dhenat  dokumentit',
        meta_tab : 'Te pergjithshme',
        appearance_tab : 'Pamja',
        advanced_tab : 'E avancuar',
        meta_props : 'Informacioni Meta',
        langprops : 'Gjuha dhe kodimi',
        meta_title : 'Titulli',
        meta_keywords : 'Fjalet çeles',
        meta_description : 'Pershkrimi',
        meta_robots : 'Robotet',
        doctypes : 'Tipi i Documentit',
        langcode : 'Kodi i gjuhes',
        langdir : 'Drejtimi i gjuhes',
        ltr : 'Nga e majta ne te djathte',
        rtl : 'Nga e djathta ne te majte',
        xml_pi : 'Deklarimi XML',
        encoding : 'Kodimi i karaktereve',
        appearance_bgprops : 'Te dhenat e sfondit',
        appearance_marginprops : 'Cepat e \'Body\'',
        appearance_linkprops : 'Ngjyrat e lidhjes',
        appearance_textprops : 'Te dhenat e tekstit',
        bgcolor : 'Ngjyra e sfondit',
        bgimage : 'Imazhi ne sfond',
        left_margin : 'Cepi i majte',
        right_margin : 'Cepi i djathe',
        top_margin : 'Cepi i siperm',
        bottom_margin : 'Cepi i poshtem',
        text_color : 'Ngjyra e tekstit',
        font_size : 'Madhesia e fontit',
        font_face : 'Fytyra e fontit',
        link_color : 'Ngjyra e lidhjes'',
        hover_color : 'Ngjyra e siperme',
        visited_color : 'Ngjyra e vizituar',
        active_color : 'Ngjyra aktive',
        textcolor : 'Ngjyra',
        fontsize : 'Madhesia e fontit',
        fontface : 'Familja  e fontit',
        meta_index_follow : 'Indekso dhe ndiq lidhjet',
        meta_index_nofollow : 'Indekso dhe mos ndiq lidhjet',
        meta_noindex_follow : 'Mos indekso dhe ndiq lidhjet',
        meta_noindex_nofollow : 'Mos indekso dhe mos ndiq lidhjet',
        appearance_style : 'Te dhenat e stilimeve dhe stileve',
        stylesheet : 'Stilim',
        style : 'Stili',
        author : 'Autori',
        copyright : 'E drejte',
        add : 'Shto nje element',
        remove : 'Hiq elementin e zgjedhur',
        moveup : 'Levize elmentin e zgjedhur lart',
        movedown : 'Levize elmentin e zgjedhur poshte',
        head_elements : 'Elementet e kokes',
        info : 'Informacion',
        info_text : '',
        add_title : 'Elementi \'Title\'',
        add_meta : 'Elementi \'Meta\'',
        add_script : 'Elementi Skript',
        add_style : 'Elementi \'Style\'',
        add_link : 'Elementi \'Link\'',
        add_base : 'Elementi \'Base\'',
        add_comment : 'Nyeja \'Comment\'',
        title_element : 'Elementi \'Title\'',
        script_element : 'Elementi \'Script\'',
        style_element : 'Elementi \'Style\'',
        base_element : 'Elementi \'Base\'',
        link_element : 'Elementi \'Link\'',
        meta_element : 'Elementi \'Meta\'',
        comment_element : 'Comment',
        src : 'Src',
        language : 'Language',
        href : 'Href',
        target : 'Target',
        rel : 'Rel',
        type : 'Type',
        charset : 'Charset',
        defer : 'Defer',
        media : 'Media',
        properties : 'Properties',
        name : 'Name',
        value : 'Value',
        content : 'Content',
        rel : 'Rel',
        rev : 'Rev',
        hreflang : 'Href lang',
        general_props : 'General',
        advanced_props : 'Advanced',
        delta_width : 0,
        delta_height : 0
});