// SR lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Podešavanja dokumenta',
	desc : 'Podešavanja dokumenta',
	meta_tab : 'Generalno',
	appearance_tab : 'Izgled',
	advanced_tab : 'Napredno',
	meta_props : 'Meta informacije',
	langprops : 'Jezik i encoding',
	meta_title : 'Naslov',
	meta_keywords : 'Ključne reči',
	meta_description : 'Opis',
	meta_robots : 'Roboti',
	doctypes : 'Doctype',
	langcode : 'Jezički kod',
	langdir : 'Jezički pravac',
	ltr : 'Levo ka desno',
	rtl : 'Desno ka levo',
	xml_pi : 'XML deklaracija',
	encoding : 'Enkoding',
	appearance_bgprops : 'Podešavanja pozadine',
	appearance_marginprops : 'Margine',
	appearance_linkprops : 'Boje linka',
	appearance_textprops : 'Podešavanja teksta',
	bgcolor : 'Pozadinska boja',
	bgimage : 'Pozadinska slika',
	left_margin : 'Leva margina',
	right_margin : 'Desna margina',
	top_margin : 'Gornja margina',
	bottom_margin : 'Donja margina',
	text_color : 'Boja teksta',
	font_size : 'Veličina fonta',
	font_face : 'Izgled fonta',
	link_color : 'Boja linka',
	hover_color : 'Hover boja',
	visited_color : 'Posećen link boja',
	active_color : 'Aktivni link boja',
	textcolor : 'Boja',
	fontsize : 'Veličina fonta',
	fontface : 'Izgled fonta',
	meta_index_follow : 'Index i praćenje linkova',
	meta_index_nofollow : 'Index i ne praćenje linkova',
	meta_noindex_follow : 'Bez indeksa ali praćenje linkova',
	meta_noindex_nofollow : 'Bez indeksa i bez praćenja linkova',
	appearance_style : 'Stil i podešavanja stilova',
	stylesheet : 'Stilovi',
	style : 'Stil',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'Dodavanje novog elementa',
	remove : 'Izbacivanje odabranog elementa',
	moveup : 'Pomeranje odabranog elementa gore',
	movedown : 'Pomeranje odabranog elementa dole',
	head_elements : 'Elementi head-a',
	info : 'Informacije',
	info_text : '',
	add_title : 'Title element',
	add_meta : 'Meta element',
	add_script : 'Script element',
	add_style : 'Style element',
	add_link : 'Link element',
	add_base : 'Base element',
	add_comment : 'Comment čvor',
	title_element : 'Title element',
	script_element : 'Script element',
	style_element : 'Style element',
	base_element : 'Base element',
	link_element : 'Link element',
	meta_element : 'Meta element',
	comment_element : 'Comment',
	src : 'Src',
	language : 'Language',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Type',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Podešavanja',
	name : 'Ime',
	value : 'Vrednost',
	content : 'Sadržaj',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Generalno',
	advanced_props : 'Napredno',
	delta_width : 0,
	delta_height : 0
});
