// UK lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Властивості документа',
	desc : 'Властивості документа',
	meta_tab : 'Основні',
	appearance_tab : 'Видимість',
	advanced_tab : 'Додаткові',
	meta_props : 'Мета інформація',
	langprops : 'Мова і кодування',
	meta_title : 'Назва',
	meta_keywords : 'Ключове слово',
	meta_description : 'Опис',
	meta_robots : 'Роботи',
	doctypes : 'Тип документа (Doctype)',
	langcode : 'Код мови',
	langdir : 'Напрямок письма',
	ltr : 'Зліва направо',
	rtl : 'Справа наліво',
	xml_pi : 'XML декларація',
	encoding : 'Кодування',
	appearance_bgprops : 'Властивості фону',
	appearance_marginprops : 'Відступи',
	appearance_linkprops : 'Колір посилань',
	appearance_textprops : 'Властивості тексту',
	bgcolor : 'Колір фону',
	bgimage : 'Фонове зображення',
	left_margin : 'Відступ зліва',
	right_margin : 'Відступ справа',
	top_margin : 'Відступ згори',
	bottom_margin : 'Відступ знизу',
	text_color : 'Колір тексту',
	font_size : 'Розмір шрифту',
	font_face : 'Шрифт',
	link_color : 'Колір посилання',
	hover_color : 'Колір при наведенні на посилання',
	visited_color : 'Колір відвідуваного посилання',
	active_color : 'Колір активного посилання',
	textcolor : 'Колір',
	fontsize : 'Розмір шрифту',
	fontface : 'Тип шрифту',
	meta_index_follow : 'Індексувати і йти за посиланнями',
	meta_index_nofollow : 'Індексувати і не йти за посиланнями',
	meta_noindex_follow : 'Не індексувати, але йти за посиланнями',
	meta_noindex_nofollow : 'Не індексувати і не йти за посиланнями',
	appearance_style : 'Таблиця стилів й властивості стилю',
	stylesheet : 'Таблиця стилів',
	style : 'Стиль',
	author : 'Автор',
	copyright : 'Авторське право',
	add : 'Додати новий елемент',
	remove : 'Видалити обраний елемент',
	moveup : 'Перемістити обраний елемент вгору',
	movedown : 'Перемістити обраний елемент вниз',
	head_elements : 'Елемент головний',
	info : 'Інформація',
	info_text : '',
	add_title : 'Елемент назва',
	add_meta : 'Елемент позначка',
	add_script : 'Елемент скрипт',
	add_style : 'Елемент стиль',
	add_link : 'Елемент посилання',
	add_base : 'Елемент базовий',
	add_comment : 'Елемент коментар',
	title_element : 'Елемент назва',
	script_element : 'Елемент скрипт',
	style_element : 'Елемент стиль',
	base_element : 'Елемент базовий',
	link_element : 'Елемент посилання',
	meta_element : 'Елемент позначка',
	comment_element : 'Коментар',
	src : 'Джерело',
	language : 'Мова',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Тип',
	charset : 'Кодування',
	defer : 'Затримка',
	media : 'Медіа',
	properties : 'Властивості',
	name : 'Ім\'я',
	value : 'Значення',
	content : 'Контент',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Основні',
	advanced_props : 'Додаткові',
	delta_width : 0,
	delta_height : 0
});
