// UK lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Властивост╕ документа',
	desc : 'Властивост╕ документа',
	meta_tab : 'Основн╕',
	appearance_tab : 'Видим╕сть',
	advanced_tab : 'Додатков╕',
	meta_props : 'Мета ╕нформац╕я',
	langprops : 'Мова ╕ кодування',
	meta_title : 'Назва',
	meta_keywords : 'Ключове слово',
	meta_description : 'Опис',
	meta_robots : 'Роботи',
	doctypes : 'Тип документа (Doctype)',
	langcode : 'Код мови',
	langdir : 'Напрямок письма',
	ltr : 'Зл╕ва направо',
	rtl : 'Справа нал╕во',
	xml_pi : 'XML декларац╕я',
	encoding : 'Кодування',
	appearance_bgprops : 'Властивост╕ фону',
	appearance_marginprops : 'В╕дступи',
	appearance_linkprops : 'Кол╕р посилань',
	appearance_textprops : 'Властивост╕ тексту',
	bgcolor : 'Кол╕р фону',
	bgimage : 'Фонове зображення',
	left_margin : 'В╕дступ зл╕ва',
	right_margin : 'В╕дступ справа',
	top_margin : 'В╕дступ згори',
	bottom_margin : 'В╕дступ знизу',
	text_color : 'Кол╕р тексту',
	font_size : 'Розм╕р шрифту',
	font_face : 'Шрифт',
	link_color : 'Кол╕р посилання',
	hover_color : 'Кол╕р при наведенн╕ на посилання',
	visited_color : 'Кол╕р в╕дв╕дуваного посилання',
	active_color : 'Кол╕р активного посилання',
	textcolor : 'Кол╕р',
	fontsize : 'Розм╕р шрифту',
	fontface : 'Тип шрифту',
	meta_index_follow : '╤ндексувати ╕ йти за посиланнями',
	meta_index_nofollow : '╤ндексувати ╕ не йти за посиланнями',
	meta_noindex_follow : 'Не ╕ндексувати, але йти за посиланнями',
	meta_noindex_nofollow : 'Не ╕ндексувати ╕ не йти за посиланнями',
	appearance_style : 'Таблиця стил╕в й властивост╕ стилю',
	stylesheet : 'Таблиця стил╕в',
	style : 'Стиль',
	author : 'Автор',
	copyright : 'Авторське право',
	add : 'Додати новий елемент',
	remove : 'Видалити обраний елемент',
	moveup : 'Перем╕стити обраний елемент вгору',
	movedown : 'Перем╕стити обраний елемент вниз',
	head_elements : 'Елемент головний',
	info : '╤нформац╕я',
	info_text : '',
	add_title : 'Елемент назва',
	add_meta : 'Елемент позначка',
	add_script : 'Елемент скрипт',
	add_style : 'Елемент стиль',
	add_link : 'Елемент посилання',
	add_base : 'Елемент базовий',
	add_comment : 'Елемент коментар',
	title_element : 'Елемент назва',
	script_element : 'Елемент скрипт',
	style_element : 'Елемент стиль',
	base_element : 'Елемент базовий',
	link_element : 'Елемент посилання',
	meta_element : 'Елемент позначка',
	comment_element : 'Коментар',
	src : 'Джерело',
	language : 'Мова',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Тип',
	charset : 'Кодування',
	defer : 'Затримка',
	media : 'Мед╕а',
	properties : 'Властивост╕',
	name : '╤м\'я',
	value : 'Значення',
	content : 'Контент',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Основн╕',
	advanced_props : 'Додатков╕',
	delta_width : 0,
	delta_height : 0
});
