/**
 * ES lang variables
 * 
 * Authors : Eneko Castresana Vara
 * Last Updated : July 14, 2006
 * TinyMCE Version : 2.0.6.1
 */

tinyMCE.addToLang('style',{
title : 'Editar estilo CSS',
styleinfo_desc : 'Editar estilo CSS',
text_tab : 'Texto',
background_tab : 'Fondo',
block_tab : 'Bloque',
box_tab : 'Cuadro',
border_tab : 'Borde',
list_tab : 'Lista',
positioning_tab : 'Posicionamiento',
text_props : 'Texto',
text_font : 'Fuente',
text_size : 'Tama&ntilde;o',
text_weight : 'Peso',
text_style : 'Estilo',
text_variant : 'Variante',
text_lineheight : 'Altura de l&iacute;nea',
text_case : 'Caso',
text_color : 'Color',
text_decoration : 'Decoraci&oacute;n',
background_color : 'Color de fondo',
background_image : 'Imagen de fondo',
background_repeat : 'Repetir',
background_attachment : 'Agregado',
background_hpos : 'Posici&oacute;n horizontal',
background_vpos : 'Posici&oacute;n vertical',
block_wordspacing : 'Espaciado de palabras',
block_letterspacing : 'Espaciado de letras',
block_vertical_alignment : 'Alineaci&oacute;n vertical',
block_text_align : 'Alineaci&oacute;n del texto',
block_text_indent : 'Indentaci&oacute;n del texto',
block_whitespace : 'Espacio',
block_display : 'Mostrar',
box_width : 'Ancho',
box_height : 'Alto',
box_float : 'Flotante',
box_clear : 'Borrar',
padding : 'Espaciado',
same : 'Igual para todo',
top : 'Arriba',
right : 'Derecha',
bottom : 'Abajo',
left : 'Izquierda',
margin : 'Margen',
style : 'Estilo',
width : 'Ancho',
height : 'Alto',
color : 'Color',
list_type : 'Tipo',
bullet_image : 'Imagen de vi&ntilde;eta',
position : 'Posici&oacute;n',
positioning_type : 'Tipo',
visibility : 'Visibilidad',
zindex : 'Z-index',
overflow : 'Desbordamiento',
placement : 'Emplazamiento',
clip : 'Recortar'
});
