// FI lang variables

tinyMCE.addToLang('style',{
title : 'Muokkaa CSS tyyli&auml;',
styleinfo_desc : 'Muokkaa CSS tyyli&auml;',
apply : 'P&auml;ivit&auml;',
text_tab : 'Teksti',
background_tab : 'Tausta',
block_tab : 'Lohko',
box_tab : 'Laatikko',
border_tab : 'Reunaviiva',
list_tab : 'Lista',
positioning_tab : 'Asettelu',
text_props : 'Teksti',
text_font : 'Kirjasin',
text_size : 'Koko',
text_weight : 'Lihavointi',
text_style : 'Tyyli',
text_variant : 'Variantti',
text_lineheight : 'Rivikorkeus',
text_case : 'Isot/pienet kirjaimet',
text_color : 'V&auml;ri',
text_decoration : 'Koristelu',
text_overline : 'ylleviivaus',
text_underline : 'alleviivaus',
text_striketrough : 'yliviivaus',
text_blink : 'vilkkuva',
text_none : 'ei mit&auml;&auml;n',
background_color : 'Taustav&auml;ri',
background_image : 'Taustakuva',
background_repeat : 'Toisto',
background_attachment : 'Kiinnitys',
background_hpos : 'Vaakasijoitus',
background_vpos : 'Pystysijoitus',
block_wordspacing : 'Sanav&auml;litys',
block_letterspacing : 'Kirjainv&auml;litys',
block_vertical_alignment : 'Pystyasettelu',
block_text_align : 'Tekstin tasaus',
block_text_indent : 'Tekstin sisennys',
block_whitespace : 'Rivitys',
block_display : 'N&auml;ytt&ouml;tapa',
box_width : 'Leveys',
box_height : 'Korkeus',
box_float : 'Float',
box_clear : 'Clear',
padding : 'T&auml;yte',
same : 'Sama kaikille',
top : 'Yl&auml;',
right : 'Oikea',
bottom : 'Ala',
left : 'Vasen',
margin : 'Marginaali',
style : 'Tyyli',
width : 'Leveys',
height : 'Korkeus',
color : 'V&auml;ri',
list_type : 'Tyyppi',
bullet_image : 'Luettelokuva',
position : 'Paikka',
positioning_type : 'Tyyppi',
visibility : 'N&auml;kyvyys',
zindex : 'Z-indeksi',
overflow : 'Overflow',
placement : 'Asettelu',
clip : 'Clip'
});
