// FR lang variables
// Modified by keyko-web.net, last updated 2007-03-08

tinyMCE.addToLang('style',{
title : 'Edtiteur de style CSS',
styleinfo_desc : 'Edtiteur de style CSS',
apply : 'Appliquer',
text_tab : 'Texte',
background_tab : 'Arri&egrave;re-plan',
block_tab : 'Bloc',
box_tab : 'Boite',
border_tab : 'Bord',
list_tab : 'Liste',
positioning_tab : 'Positionnement',
text_props : 'Texte',
text_font : 'Police',
text_size : 'Taille',
text_weight : 'Poids',
text_style : 'Style',
text_variant : 'Variant',
text_lineheight : 'Hauteur de ligne',
text_case : 'Casse',
text_color : 'Couleur',
text_decoration : 'D&eacute;coration',
text_overline : 'surlign&eacute;',
text_underline : 'soulign&eacute;',
text_striketrough : 'barr&eacute;',
text_blink : 'clignotant',
text_none : 'aucun',
background_color : 'Couleur d\'arri&egrave;re-plan',
background_image : 'Image d\'arri&egrave;re-plan',
background_repeat : 'R&eacute;p&eacute;ter',
background_attachment : 'Attacher',
background_hpos : 'Position horizontale',
background_vpos : 'Position verticale',
block_wordspacing : 'Espace entre les mots',
block_letterspacing : 'Espace entre les lettres',
block_vertical_alignment : 'Aligenement vertical',
block_text_align : 'Aligement du texte',
block_text_indent : 'Indentation du texte',
block_whitespace : 'Espace',
block_display : 'Afficher',
box_width : 'Largeur',
box_height : 'Hauteur',
box_float : 'Float',
box_clear : 'Effacer',
padding : 'Padding',
same : 'Identique pour tous',
top : 'Haut',
right : 'Droite',
bottom : 'Bas',
left : 'Gauche',
margin : 'Marge',
style : 'Style',
width : 'Largeur',
height : 'Hauteur',
color : 'Couleur',
list_type : 'Type',
bullet_image : 'Bullet image',
position : 'Position',
positioning_type : 'Type',
visibility : 'Visibilit&eacute;',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Placement',
clip : 'Clip'
});
