/**
 * IT lang variables
 * 
 * Author : Luciano Vernaschi <luciano@virgilio.it>
 * Last Updated : Mar. 1st, 2007
 * TinyMCE Version : 2.1.0
 */

tinyMCE.addToLang('style',{
title : 'Modifica stile CSS',
styleinfo_desc : 'Modifica stile CSS',
apply : 'Applica',
text_tab : 'Testo',
background_tab : 'Sfondo',
block_tab : 'Blocco',
box_tab : 'Box',
border_tab : 'Bordo',
list_tab : 'Lista',
positioning_tab : 'Posizionamento',
text_props : 'Testo',
text_font : 'Font',
text_size : 'Dimensione',
text_weight : 'Peso',
text_style : 'Stile',
text_variant : 'Variante',
text_lineheight : 'Altezza linea',
text_case : 'Caso',
text_color : 'Colore',
text_decoration : 'Decorazione',
text_overline : 'Linea sopra',
text_underline : 'Sottolinea',
text_striketrough : 'Linea sovrapposta',
text_blink : 'Lampeggia',
text_none : 'Nessuno',
background_color : 'Colore di sfondo',
background_image : 'Immagine di sfondo',
background_repeat : 'Ripeti',
background_attachment : 'Ancoraggio',
background_hpos : 'Posizione orizzontale',
background_vpos : 'Posizione verticale',
block_wordspacing : 'Spaziatura parole',
block_letterspacing : 'Spaziatura lettere',
block_vertical_alignment : 'Allineamento verticale',
block_text_align : 'Allineamento del testo',
block_text_indent : 'Indentazione del testo',
block_whitespace : 'Whitespace',
block_display : 'Display',
box_width : 'Larghezza',
box_height : 'Altezza',
box_float : 'Float',
box_clear : 'Clear',
padding : 'Spaziatura interna',
same : 'Uguale per tutti',
top : 'Alto',
right : 'Destra',
bottom : 'Basso',
left : 'Sinistra',
margin : 'Margine esterno',
style : 'Stile',
width : 'Larghezza',
height : 'Altezza',
color : 'Colore',
list_type : 'Tipo',
bullet_image : 'Immagine punto elenco',
position : 'Posizionamento',
positioning_type : 'Tipo',
visibility : 'Visibilit&agrave;',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Piazzamento',
clip : 'Clip'
});
