/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('style',{
title : 'Editar folha de estilo CSS',
styleinfo_desc : 'Editar estilo CSS',
apply : 'Aplicar',
text_tab : 'Texto',
background_tab : 'Fundo',
block_tab : 'Bloco',
box_tab : 'Caixa',
border_tab : 'Borda',
list_tab : 'Lista',
positioning_tab : 'Posicionamento',
text_props : 'Texto',
text_font : 'Fonte',
text_size : 'Tamanho',
text_weight : 'Largura',
text_style : 'Estilo',
text_variant : 'Variação',
text_lineheight : 'Altura da linha',
text_case : 'Caso',
text_color : 'Cor',
text_decoration : 'Decoração',
text_overline : 'Sobrescrito',
text_underline : 'Subscrito',
text_striketrough : 'Tachado',
text_blink : 'Piscante',
text_none : 'nenhum',
background_color : 'Cor do fundo',
background_image : 'Fundo da imagem',
background_repeat : 'Repetir',
background_attachment : 'Anexo',
background_hpos : 'Posição horizontal',
background_vpos : 'Posição vertical',
block_wordspacing : 'Espaçamento de palavras',
block_letterspacing : 'Espaçamento de letras',
block_vertical_alignment : 'Alinhamento vertical',
block_text_align : 'Alinhamento do texto',
block_text_indent : 'Identação do texto',
block_whitespace : 'Espaços em branco',
block_display : 'Visualização',
box_width : 'Largura',
box_height : 'Altura',
box_float : 'Flutuante',
box_clear : 'Limpar',
padding : 'Espaçamento',
same : 'Igual para todos',
top : 'Superior',
right : 'Direita',
bottom : 'Inferior',
left : 'Esquerda',
margin : 'Margem',
style : 'Estilo',
width : 'Largura',
height : 'Altura',
color : 'Cor',
list_type : 'Tipo',
bullet_image : 'Imagem tipo Bullet',
position : 'Posicionamento',
positioning_type : 'Tipo',
visibility : 'Visibilidade',
zindex : 'Z-index',
overflow : 'Sobrescrever',
placement : 'Localização',
clip : 'Clip'
});
