// RO lang variables

tinyMCE.addToLang('style',{
title : 'Editare stil CSS',
styleinfo_desc : 'Editare stil CSS',
apply : 'Aplic&#259;',
text_tab : 'Text',
background_tab : 'Fundal',
block_tab : 'Bloc',
box_tab : 'Cutie',
border_tab : 'Chenar',
list_tab : 'List&#259;',
positioning_tab : 'Pozi&#355;ionare',
text_props : 'Text',
text_font : 'Font',
text_size : 'Dimensiune',
text_weight : 'Greutate',
text_style : 'Stil',
text_variant : 'Variant&#259;',
text_lineheight : '&#206;n&#259;l&#355;ime linie',
text_case : 'Minuscule/majuscule',
text_color : 'Culoare',
text_decoration : 'Decora&#255;ie',
text_overline : 't&#259;iat',
text_underline : 'subliniat',
text_striketrough : 't&#259;iat',
text_blink : 'clipe&#351;te',
text_none : 'nimic',
background_color : 'Culoare fundal',
background_image : 'Imagine fundal',
background_repeat : 'Repet&#259;',
background_attachment : 'Ata&#351;ament',
background_hpos : 'Pozi&#255;ia pa orizontal&#259;',
background_vpos : 'Pozi&#355;ia pe vertical&#259;',
block_wordspacing : 'Spa&#355;ierea cuvintelor',
block_letterspacing : 'Spa&#355;erea literelor',
block_vertical_alignment : 'Aliniere vertical&#259;',
block_text_align : 'Aliniere text',
block_text_indent : 'Indentare text',
block_whitespace : 'Spa&#355;iu alb',
block_display : 'Afi&#351;are',
box_width : 'L&#259;&#355;ime',
box_height : '&#206;n&#259;l&#355;ime',
box_float : 'Plutitor',
box_clear : 'Curat',
padding : 'Umplere (padding)',
same : 'La fel peste tot',
top : 'Sus',
right : 'Dreapta',
bottom : 'Jos',
left : 'St&#226;nga',
margin : 'Margine',
style : 'Stil',
width : 'L&#259;&#355;ime',
height : '&#206;n&#259;l&#355;ime',
color : 'Culoare',
list_type : 'Tip',
bullet_image : 'Imagine bullet',
position : 'Pozi&#355;ia',
positioning_type : 'Tip',
visibility : 'Vizibilitate',
zindex : 'Z-index',
overflow : 'Dep&#259;&#351;ire (overflow)',
placement : 'Plasare',
clip : 'Clip'
});
