// RU lang variables

tinyMCE.addToLang('style',{
title : 'Редактировать CSS Стиль',
styleinfo_desc : 'Редактировать CSS Стиль',
apply : 'Принять',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Граница',
list_tab : 'Список',
positioning_tab : 'Позиционирование',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Размер',
text_weight : 'Ширина',
text_style : 'Стиль',
text_variant : 'Вариант',
text_lineheight : 'Высота строки',
text_case : 'Регистр',
text_color : 'Цвет',
text_decoration : 'Оформление',
text_overline : 'Надчеркивание',
text_underline : 'Подчеркивание',
text_striketrough : 'Зачеркивание',
text_blink : 'Мерцание',
text_none : 'нет',
background_color : 'Цвет фона',
background_image : 'Фоновое изображение',
background_repeat : 'Повторить',
background_attachment : 'Прокрутка фонового изображения',
background_hpos : 'Горизонтальная позиция',
background_vpos : 'Вертикальная позиция',
block_wordspacing : 'Расстояние между словами',
block_letterspacing : 'Расстояние между буквами',
block_vertical_alignment : 'Выравнивание по вертикали',
block_text_align : 'Выравнивание текста',
block_text_indent : 'Отступ первой строки',
block_whitespace : 'Пробелы',
block_display : 'Отображение',
box_width : 'Ширина',
box_height : 'Высота',
box_float : 'Выравнивание с обтеканием',
box_clear : 'Запрет обтекания',
padding : 'Поля',
same : 'Тоже для остальных',
top : 'Верх',
right : 'Право',
bottom : 'Низ',
left : 'Лево',
margin : 'Отступ',
style : 'Стиль',
width : 'Ширина',
height : 'Высота',
color : 'Цвет',
list_type : 'Тип',
bullet_image : 'Маркер абзаца',
position : 'Позиция',
positioning_type : 'Тип',
visibility : 'Видимость',
zindex : 'Наложение',
overflow : 'Переполнение',
placement : 'Размещение',
clip : 'Позиционирование'
});
