// UK lang variables

tinyMCE.addToLang('style',{
title : 'Ndrysho stilin CSS',
styleinfo_desc : 'Ndrysho stilin CSS',
text_tab : 'Teksti',
background_tab : 'Sfondi',
block_tab : 'Blloku',
box_tab : 'Kutia',
border_tab : 'Kufiri',
list_tab : 'Lista',
positioning_tab : 'Pozicionimi',
text_props : 'Teksti',
text_font : 'Fonti',
text_size : 'Madhesia',
text_weight : 'Tipi',
text_style : 'Stili',
text_variant : 'Varianti',
text_lineheight : 'Trashesia e linjes',
text_case : 'E madhe/vogel',
text_color : 'Ngjyra',
text_decoration : 'Dekorimi',
background_color : 'Ngjyra e sfondit',
background_image : 'Imazhi ne sfond',
background_repeat : 'Perserit',
background_attachment : 'Bashkangjitur',
background_hpos : 'Pozicioni horizontal',
background_vpos : 'Pozicioni vertikal',
block_wordspacing : 'Hapesira e fjaleve',
block_letterspacing : 'Hapesira e germave',
block_vertical_alignment : 'Dreitimi vertikal',
block_text_align : 'Drejtimi i tekstit',
block_text_indent : 'Hapesira e tekstit',
block_whitespace : 'Hpaseira e bardhe',
block_display : 'Pamja',
box_width : 'Gjersia',
box_height : 'Lartesia',
box_float : 'Noto',
box_clear : 'Bosh',
padding : 'Vend bosh',
same : 'Te gjithe njesoj',
top : 'Siper',
right : 'Djathtas',
bottom : 'Poshte',
left : 'Majtas',
margin : 'Buzet',
style : 'Stili',
width : 'Gjeresia',
height : 'Lartesia',
color : 'Ngjyra',
list_type : 'Tipi',
bullet_image : 'Imazhi i pikes',
position : 'Pozicioni',
positioning_type : 'Tipi',
visibility : 'Dukshmeria',
zindex : 'Indeksi-Z',
overflow : 'Mbiderdhje',
placement : 'Vendosja',
clip : 'Klipi'
});