// UK lang variables

tinyMCE.addToLang('style',{
title : 'Редагувати CSS Стиль',
styleinfo_desc : 'Редагувати CSS Стиль',
apply : 'Прийняти',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Край',
list_tab : 'Список',
positioning_tab : 'Позиціонування',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Розмір',
text_weight : 'Ширина',
text_style : 'Стиль',
text_variant : 'Варіант',
text_lineheight : 'Висота рядка',
text_case : 'Регістр',
text_color : 'Колір',
text_decoration : 'Оформлення',
text_overline : 'Надкреслення',
text_underline : 'Підкреслення',
text_striketrough : 'Перекреслення',
text_blink : 'Мерехтіння',
text_none : 'немає',
background_color : 'Колір фону',
background_image : 'Фонове зображення',
background_repeat : 'Повторити',
background_attachment : 'Прокручування фонового зображення',
background_hpos : 'Горизонтальна позиція',
background_vpos : 'Вертикальна позиція',
block_wordspacing : 'Відстань між словами',
block_letterspacing : 'Відстань між літерами',
block_vertical_alignment : 'Вирівнювання за вертикаллю',
block_text_align : 'Вирівнювання тексту',
block_text_indent : 'Відступ першого рядка',
block_whitespace : 'Пробіли',
block_display : 'Відображення',
box_width : 'Ширина',
box_height : 'Висота',
box_float : 'Вирівнювання з обтіканням',
box_clear : 'Заборона обтікання',
padding : 'Поля',
same : 'Те ж для інших',
top : 'Зверху',
right : 'Справа',
bottom : 'Знизу',
left : 'Зліва',
margin : 'Відступ',
style : 'Стиль',
width : 'Ширина',
height : 'Висота',
color : 'Колір',
list_type : 'Тип',
bullet_image : 'Маркер абзацу',
position : 'Позиція',
positioning_type : 'Тип',
visibility : 'Видимість',
zindex : 'Накладення',
overflow : 'Переповнення',
placement : 'Розміщення',
clip : 'Позиціонування'
});
