// UK lang variables

tinyMCE.addToLang('style',{
title : 'Редагувати CSS Стиль',
styleinfo_desc : 'Редагувати CSS Стиль',
apply : 'Прийняти',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Край',
list_tab : 'Список',
positioning_tab : 'Позиц╕онування',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Розм╕р',
text_weight : 'Ширина',
text_style : 'Стиль',
text_variant : 'Вар╕ант',
text_lineheight : 'Висота рядка',
text_case : 'Рег╕стр',
text_color : 'Кол╕р',
text_decoration : 'Оформлення',
text_overline : 'Надкреслення',
text_underline : 'П╕дкреслення',
text_striketrough : 'Перекреслення',
text_blink : 'Мерехт╕ння',
text_none : 'нема╓',
background_color : 'Кол╕р фону',
background_image : 'Фонове зображення',
background_repeat : 'Повторити',
background_attachment : 'Прокручування фонового зображення',
background_hpos : 'Горизонтальна позиц╕я',
background_vpos : 'Вертикальна позиц╕я',
block_wordspacing : 'В╕дстань м╕ж словами',
block_letterspacing : 'В╕дстань м╕ж л╕терами',
block_vertical_alignment : 'Вир╕внювання за вертикаллю',
block_text_align : 'Вир╕внювання тексту',
block_text_indent : 'В╕дступ першого рядка',
block_whitespace : 'Проб╕ли',
block_display : 'В╕дображення',
box_width : 'Ширина',
box_height : 'Висота',
box_float : 'Вир╕внювання з обт╕канням',
box_clear : 'Заборона обт╕кання',
padding : 'Поля',
same : 'Те ж для ╕нших',
top : 'Зверху',
right : 'Справа',
bottom : 'Знизу',
left : 'Зл╕ва',
margin : 'В╕дступ',
style : 'Стиль',
width : 'Ширина',
height : 'Висота',
color : 'Кол╕р',
list_type : 'Тип',
bullet_image : 'Маркер абзацу',
position : 'Позиц╕я',
positioning_type : 'Тип',
visibility : 'Видим╕сть',
zindex : 'Накладення',
overflow : 'Переповнення',
placement : 'Розм╕щення',
clip : 'Позиц╕онування'
});
