// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('style',{
title : 'Sửa phong cách - CSS',
styleinfo_desc : 'Sửa phong cách - CSS',
apply : 'Áp dụng',
text_tab : 'Chữ',
background_tab : 'Nền',
block_tab : 'Khối',
box_tab : 'Hộp',
border_tab : 'Khung bao quanh',
list_tab : 'Danh sách',
positioning_tab : 'Vị trí',
text_props : 'Chữ',
text_font : 'Font',
text_size : 'Cỡ',
text_weight : 'Độ đậm',
text_style : 'Kiểu',
text_variant : 'Variant',
text_lineheight : 'Khoảng cách dòng',
text_case : 'Case',
text_color : 'Màu',
text_decoration : 'Decoration',
text_overline : 'overline',
text_underline : 'gạch chân',
text_striketrough : 'gạch ngang qua',
text_blink : 'nhấp nháy',
text_none : 'không có gì',
background_color : 'Màu nền',
background_image : 'Ảnh nền',
background_repeat : 'Lặp lại',
background_attachment : 'Đính kèm',
background_hpos : 'Vị trí nằm ngang',
background_vpos : 'Vị trí nằm dọc',
block_wordspacing : 'Khoảng cách từ',
block_letterspacing : 'Khoảng cách chữ',
block_vertical_alignment : 'Căn lề chiều dọc',
block_text_align : 'Căn lề chữ',
block_text_indent : 'Thụt lề chữ',
block_whitespace : 'Khoảng trắng',
block_display : 'Hiển thị',
box_width : 'Chiều rộng',
box_height : 'Chiều cao',
box_float : 'Lơ lửng',
box_clear : 'Clear',
padding : 'Padding',
same : 'Áp dụng cho tất cả',
top : 'Trên',
right : 'Phải',
bottom : 'Dưới',
left : 'Trái',
margin : 'Lề',
style : 'Kiểu',
width : 'Độ rộng',
height : 'Chiều cao',
color : 'Màu',
list_type : 'Kiểu',
bullet_image : 'Ảnh danh sách',
position : 'Vị trí',
positioning_type : 'Kiểu',
visibility : 'Nhìn thấy được',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Vị trí',
clip : 'Cắt'
});
