name: Auto-delete feature branches

permissions:
  contents: write

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check for feature branch
        id: branch-check
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != feature ]]; then
            echo "::notice::Skipping non-feature branch"
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Delete branch
        if: steps.branch-check.outputs.skip != 'true'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}  # Use the default token
          branches: ${{ github.event.pull_request.head.ref }}
