name: Auto-delete feature branches

permissions:
  contents: write

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check for feature branch
        id: branch-check
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != feature/* ]]; then
            echo "::notice::Skipping non-feature branch"
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Delete branch
        if: steps.branch-check.outputs.skip != 'true'
        id: delete-branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: ${{ github.event.pull_request.head.ref }}

      - name: Mark job success
        if: always()
        run: |
          if [[ "${{ steps.delete-branch.outcome }}" == 'success' || "${{ steps.branch-check.outputs.skip }}" == 'true' ]]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi