name: PR Gatekeeper
on:
  pull_request_target:
    branches: [recette]
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        id: check-branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "dev" ]; then
            echo "::error::PRs to recette must come from dev branch!"
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "❌ Invalid source branch. Only PRs from `dev` are allowed to merge into `recette`."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-label valid PRs
        if: steps.check-branch.outcome == 'success'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "recette-merge" \
            --body "This PR meets the recette merge criteria."
