name: PR Gatekeeper
on:
  pull_request_target:
    branches: [recette]

permissions:
  pull-requests: write
  issues: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source
        id: check-branch
        run: |
          [ "${{ github.event.pull_request.head.ref }}" = "dev" ] || exit 1

      - name: Label valid PR
        if: steps.check-branch.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "recette-merge" \
            --body "Updated: This PR meets all merge criteria for recette"
